from pathlib import Path
import re

from getpycode import CodeGenerator, ImportBuilder, AbstractComment, Package, Module  # noqa
from jinja2 import FileSystemLoader  # noqa

from apicodegen.documentation.documentation import Documentation
from apicodegen.generation.preparation.types import PreparedType, PreparedMethod
from apicodegen.generation.preparation.preparation import (
    prepare_type,
    prepare_method,
    get_update_types,
    get_snake_case_string,
    MESSAGE_TYPES
)


telebox_dir = Path(__file__).parent.parent.parent / "telebox"
template_dir = Path(__file__).parent / "templates"
types_dir = telebox_dir / "bot" / "types"
bot_path = telebox_dir / "bot" / "bot.py"
message_type_path = telebox_dir / "bot" / "enums" / "message_type.py"
update_type_path = telebox_dir / "bot" / "enums" / "update_type.py"
dispatcher_path = telebox_dir / "dispatcher" / "dispatcher.py"
router_path = telebox_dir / "dispatcher" / "router.py"
type_hints_path = telebox_dir / "dispatcher" / "type_hints.py"
event_type_path = telebox_dir / "dispatcher" / "enums" / "event_type.py"
STATE_EVENT_TYPES = [
    "MESSAGE",
    "EDITED_MESSAGE",
    "CHANNEL_POST",
    "EDITED_CHANNEL_POST",
    "CALLBACK_QUERY",
    "MEDIA_GROUP",
    "CHANNEL_MEDIA_GROUP"
]


class Comment(AbstractComment):
    def get(self, module: Module) -> list[str]:
        return [
            "This file was automatically generated by `apicodegen`.",
            "DO NOT EDIT THIS FILE MANUALLY!"
        ]


def create_code(documentation: Documentation) -> None:
    bot_import_builder = ImportBuilder("telebox")
    type_import_builders = {
        i.name: ImportBuilder(
            "telebox",
            exclude=(
                f"telebox.bot.types.{get_snake_case_string(i.name)}",
                i.name
            )
        )
        for i in documentation.types
    }

    prepared_methods = [
        prepare_method(
            method=i,
            type_names=documentation.type_names,
            import_builder=bot_import_builder
        )
        for i in documentation.methods
    ]
    prepared_types = {
        i.name: prepare_type(
            type_=i,
            type_names=documentation.type_names,
            import_builder=type_import_builders[i.name]
        )
        for i in documentation.types
    }
    update_types = get_update_types(prepared_types["Update"])
    event_types = _get_event_types(update_types)

    generator = CodeGenerator(
        loader=FileSystemLoader(template_dir),
        comment=Comment()
    )

    _create_types_package(
        generator=generator,
        import_builders=type_import_builders,
        types=prepared_types
    )
    _create_bot_module(
        generator=generator,
        import_builder=bot_import_builder,
        methods=prepared_methods
    )
    _create_message_type_module(
        generator=generator
    )
    _create_update_type_module(
        generator=generator,
        types=update_types
    )
    _create_event_type_module(
        generator=generator,
        types=event_types
    )
    _create_dispatcher_module(
        generator=generator,
        event_types=event_types
    )
    _create_router_module(
        generator=generator,
        event_types=event_types
    )
    _create_type_hints_module(
        generator=generator,
        hint_types=_get_event_hint_types(
            update=prepared_types["Update"]
        )
    )


def _create_types_package(
    generator: CodeGenerator,
    import_builders: dict[str, ImportBuilder],
    types: dict[str, PreparedType]
) -> None:
    init_import_builder = ImportBuilder("telebox")
    init_import_builder.add("typing", "get_type_hints")

    for i in types.values():
        init_import_builder.add(f".{i.module_name}", i.name)

    evaluating_types = _resolve_message_type_hints(types, import_builders)
    package = Package(
        types_dir,
        "bot/types/__init__.j2",
        imports=init_import_builder.get(),
        types=types,
        evaluating_types=sorted(evaluating_types)
    )

    for type_ in types:
        if type_ == "InputFile":
            continue

        if not types[type_].is_union:
            import_builders[type_].add("attrs", "define")
            import_builders[type_].add("telebox.bot.type", "Type")

            if types[type_].fields:
                import_builders[type_].add("attrs", "field")

            if import_builders[type_].check("telebox.utils.unset", "Unset"):
                import_builders[type_].add("telebox.bot.type", "default_factory")

        package.add_module(
            f"{types[type_].module_name}.py",
            "bot/types/type.j2",
            imports=import_builders[type_].get(),
            type_=types[type_]
        )

    generator.create_package(package)


def _create_bot_module(
    generator: CodeGenerator,
    import_builder: ImportBuilder,
    methods: list[PreparedMethod]
) -> None:
    import_builder.add("telebox.bot.converter", "Converter")

    for i in ("Session", "API_URL"):
        import_builder.add("telebox.bot.session", i)

    # For `download_file` method
    import_builder.add("typing", "BinaryIO")

    # For context values
    for i in ("CONTEXT", "OPTIONAL_CONTEXT"):
        import_builder.add("telebox.dispatcher.context", i)

    # For default values
    import_builder.add("telebox.utils.unset", "UNSET")
    import_builder.add("telebox.bot.default_parameters", "DefaultParameterSet")

    # For `profile` property
    import_builder.add("telebox.bot.errors", "BotError")

    generator.create_module(
        Module(
            bot_path,
            "bot/bot.j2",
            imports=import_builder.get(),
            methods=methods
        )
    )


def _create_message_type_module(
    generator: CodeGenerator
) -> None:
    generator.create_module(
        Module(
            message_type_path,
            "enum.j2",
            class_="MessageType",
            types=MESSAGE_TYPES
        )
    )


def _create_update_type_module(
    generator: CodeGenerator,
    types: list[str]
) -> None:
    generator.create_module(
        Module(
            update_type_path,
            "enum.j2",
            class_="UpdateType",
            types=types
        )
    )


def _create_event_type_module(
    generator: CodeGenerator,
    types: list[str]
) -> None:
    generator.create_module(
        Module(
            event_type_path,
            "enum.j2",
            class_="EventType",
            types=types
        )
    )


def _create_dispatcher_module(
    generator: CodeGenerator,
    event_types: list[str]
) -> None:
    generator.create_module(
        Module(
            dispatcher_path,
            "dispatcher/dispatcher.j2",
            event_types=event_types,
            state_event_types=STATE_EVENT_TYPES
        )
    )


def _create_router_module(
    generator: CodeGenerator,
    event_types: list[str]
) -> None:
    generator.create_module(
        Module(
            router_path,
            "dispatcher/router.j2",
            event_types=event_types,
            state_event_types=STATE_EVENT_TYPES
        )
    )


def _create_type_hints_module(
    generator: CodeGenerator,
    hint_types: list[str]
) -> None:
    import_builder = ImportBuilder("telebox")

    for i in ("Union", "Callable"):
        import_builder.add("typing", i)

    for i in hint_types:
        if i == "MediaGroup":
            import_builder.add("telebox.dispatcher.types.media_group", "MediaGroup")
        else:
            import_builder.add(f"telebox.bot.types.{get_snake_case_string(i)}", i)

    import_builder.add("telebox.utils.deps", "Deps")

    generator.create_module(
        Module(
            type_hints_path,
            "dispatcher/type_hints.j2",
            imports=import_builder.get(),
            hint_types=hint_types
        )
    )


def _get_event_types(update_types: list[str]) -> list[str]:
    types = update_types[:]

    for i in ("MEDIA_GROUP", "CHANNEL_MEDIA_GROUP"):
        types.append(i)

    return sorted(types)


def _get_event_hint_types(update: PreparedType) -> list[str]:
    types = {
        i.types[0]
        for i in update.fields
        if i.is_optional
    }
    types.add("MediaGroup")

    return sorted(types)


def _resolve_message_type_hints(
    types: dict[str, PreparedType],
    import_builders: dict[str, ImportBuilder]
) -> set[str]:
    message = types["Message"]
    message_import_builder = import_builders["Message"]
    evaluating_types = {"Message"}

    for i in message.fields:
        i.type_hint = re.sub(r"\bMessage\b", '"Message"', i.type_hint)

    for type_ in types:
        if not import_builders[type_].check("telebox.bot.types.message", "Message"):
            continue

        for i in message.fields:
            if not message_import_builder.check(
                f"telebox.bot.types.{types[type_].module_name}",
                type_
            ):
                continue

            i.type_hint = re.sub(rf"\b{type_}\b", f'"{type_}"', i.type_hint)
            evaluating_types.add(type_)
            message_import_builder.add(
                f"telebox.bot.types.{types[type_].module_name}",
                type_,
                for_type_checking=True
            )

    return evaluating_types
