# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from enum import Enum


class EventType(Enum):
    BUSINESS_CONNECTION = "business_connection"
    BUSINESS_MESSAGE = "business_message"
    CALLBACK_QUERY = "callback_query"
    CHANNEL_MEDIA_GROUP = "channel_media_group"
    CHANNEL_POST = "channel_post"
    CHAT_BOOST = "chat_boost"
    CHAT_JOIN_REQUEST = "chat_join_request"
    CHAT_MEMBER = "chat_member"
    CHOSEN_INLINE_RESULT = "chosen_inline_result"
    DELETED_BUSINESS_MESSAGES = "deleted_business_messages"
    EDITED_BUSINESS_MESSAGE = "edited_business_message"
    EDITED_CHANNEL_POST = "edited_channel_post"
    EDITED_MESSAGE = "edited_message"
    GUEST_MESSAGE = "guest_message"
    INLINE_QUERY = "inline_query"
    MANAGED_BOT = "managed_bot"
    MEDIA_GROUP = "media_group"
    MESSAGE = "message"
    MESSAGE_REACTION = "message_reaction"
    MESSAGE_REACTION_COUNT = "message_reaction_count"
    MY_CHAT_MEMBER = "my_chat_member"
    POLL = "poll"
    POLL_ANSWER = "poll_answer"
    PRE_CHECKOUT_QUERY = "pre_checkout_query"
    PURCHASED_PAID_MEDIA = "purchased_paid_media"
    REMOVED_CHAT_BOOST = "removed_chat_boost"
    SHIPPING_QUERY = "shipping_query"
