# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class AcceptedGiftTypes(Type):
    unlimited_gifts: bool = field()
    limited_gifts: bool = field()
    unique_gifts: bool = field()
    premium_subscription: bool = field()
