# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.chat import Chat
from telebox.bot.types.user import User
from telebox.utils.unset import Unset


@define(repr=False)
class AffiliateInfo(Type):
    commission_per_mille: int = field()
    amount: int = field()
    affiliate_user: Union[User, None, Unset] = field(factory=default_factory, kw_only=True)
    affiliate_chat: Union[Chat, None, Unset] = field(factory=default_factory, kw_only=True)
    nanostar_amount: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
