# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.photo_size import PhotoSize
from telebox.bot.utils.types import default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class Animation(Type):
    file_id: str = field()
    file_unique_id: str = field()
    width: int = field()
    height: int = field()
    duration: int = field()
    thumbnail: Union[PhotoSize, None, Unset] = field(factory=default_factory, kw_only=True)
    file_name: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    mime_type: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    file_size: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
