# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Literal, Union

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.background_fill import BackgroundFill
from telebox.bot.types.document import Document
from telebox.bot.utils.types import default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class BackgroundTypePattern(Type):
    document: Document = field()
    fill: BackgroundFill = field()
    intensity: int = field()
    is_inverted: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    is_moving: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    type: Literal["pattern"] = field(default="pattern", kw_only=True)
