# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Literal

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class BackgroundTypeChatTheme(Type):
    theme_name: str = field()
    type: Literal["chat_theme"] = field(default="chat_theme", kw_only=True)
