# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Literal, Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.document import Document
from telebox.utils.unset import Unset


@define(repr=False)
class BackgroundTypeWallpaper(Type):
    document: Document = field()
    dark_theme_dimming: int = field()
    is_blurred: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    is_moving: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    type: Literal["wallpaper"] = field(default="wallpaper", kw_only=True)
