# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Literal

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class BackgroundFillFreeformGradient(Type):
    colors: list[int] = field()
    type: Literal["freeform_gradient"] = field(default="freeform_gradient", kw_only=True)
