# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from telebox.bot.types.background_type_chat_theme import BackgroundTypeChatTheme
from telebox.bot.types.background_type_fill import BackgroundTypeFill
from telebox.bot.types.background_type_pattern import BackgroundTypePattern
from telebox.bot.types.background_type_wallpaper import BackgroundTypeWallpaper


BackgroundType = Union[
    BackgroundTypeFill,
    BackgroundTypeWallpaper,
    BackgroundTypePattern,
    BackgroundTypeChatTheme
]
