# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from telebox.bot.types.background_fill_freeform_gradient import BackgroundFillFreeformGradient
from telebox.bot.types.background_fill_gradient import BackgroundFillGradient
from telebox.bot.types.background_fill_solid import BackgroundFillSolid


BackgroundFill = Union[
    BackgroundFillSolid,
    BackgroundFillGradient,
    BackgroundFillFreeformGradient
]
