# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Literal

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class BackgroundFillGradient(Type):
    top_color: int = field()
    bottom_color: int = field()
    rotation_angle: int = field()
    type: Literal["gradient"] = field(default="gradient", kw_only=True)
