# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Literal

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.background_fill import BackgroundFill


@define(repr=False)
class BackgroundTypeFill(Type):
    fill: BackgroundFill = field()
    dark_theme_dimming: int = field()
    type: Literal["fill"] = field(default="fill", kw_only=True)
