# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class Birthdate(Type):
    day: int = field()
    month: int = field()
    year: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
