# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class BotCommand(Type):
    command: str = field()
    description: str = field()
