# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class BotCommandScopeChatAdministrators(Type):
    chat_id: Union[int, str] = field()
    type: Literal["chat_administrators"] = field(default="chat_administrators", kw_only=True)
