# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Literal

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class BotCommandScopeAllPrivateChats(Type):
    type: Literal["all_private_chats"] = field(default="all_private_chats", kw_only=True)
