# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class BotCommandScopeChat(Type):
    chat_id: Union[int, str] = field()
    type: Literal["chat"] = field(default="chat", kw_only=True)
