# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Literal

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class BotCommandScopeAllChatAdministrators(Type):
    type: Literal["all_chat_administrators"] = field(default="all_chat_administrators", kw_only=True)
