# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.user import User
from telebox.unset import Unset


@define(repr=False)
class BotAccessSettings(Type):
    is_access_restricted: bool = field()
    added_users: Union[list[User], None, Unset] = field(factory=default_factory, kw_only=True)
