# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class BotCommandScopeChatMember(Type):
    chat_id: Union[int, str] = field()
    user_id: int = field()
    type: Literal["chat_member"] = field(default="chat_member", kw_only=True)
