# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Literal

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class BotCommandScopeAllGroupChats(Type):
    type: Literal["all_group_chats"] = field(default="all_group_chats", kw_only=True)
