# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.sticker import Sticker
from telebox.bot.utils.types import default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class BusinessIntro(Type):
    title: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    message: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    sticker: Union[Sticker, None, Unset] = field(factory=default_factory, kw_only=True)
