# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.location import Location
from telebox.utils.unset import Unset


@define(repr=False)
class BusinessLocation(Type):
    address: str = field()
    location: Union[Location, None, Unset] = field(factory=default_factory, kw_only=True)
