# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.chat import Chat


@define(repr=False)
class BusinessMessagesDeleted(Type):
    business_connection_id: str = field()
    chat: Chat = field()
    message_ids: list[int] = field()
