# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.business_opening_hours_interval import BusinessOpeningHoursInterval


@define(repr=False)
class BusinessOpeningHours(Type):
    time_zone_name: str = field()
    opening_hours: list[BusinessOpeningHoursInterval] = field()
