# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from datetime import datetime
from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.business_bot_rights import BusinessBotRights
from telebox.bot.types.user import User
from telebox.unset import Unset


@define(repr=False)
class BusinessConnection(Type):
    id: str = field()
    user: User = field()
    user_chat_id: int = field()
    date: datetime = field()
    is_enabled: bool = field()
    rights: Union[BusinessBotRights, None, Unset] = field(factory=default_factory, kw_only=True)
    
    @property
    def user_id(self) -> int:
        return self.user.id
