# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Literal, Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.unset import Unset


@define(repr=False)
class BusinessBotRights(Type):
    can_reply: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    can_read_messages: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    can_delete_sent_messages: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    can_delete_all_messages: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    can_edit_name: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    can_edit_bio: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    can_edit_profile_photo: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    can_edit_username: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    can_change_gift_settings: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    can_view_gifts_and_stars: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    can_convert_gifts_to_stars: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    can_transfer_and_upgrade_gifts: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    can_transfer_stars: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    can_manage_stories: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
