# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union, Optional

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.maybe_inaccessible_message import MaybeInaccessibleMessage
from telebox.bot.types.user import User
from telebox.bot.utils.ids import get_unprefixed_chat_id
from telebox.callback_data import get_parsed_callback_data
from telebox.unset import Unset


@define(repr=False)
class CallbackQuery(Type):
    id: str = field()
    from_: User = field()
    chat_instance: str = field()
    message: Union[MaybeInaccessibleMessage, None, Unset] = field(factory=default_factory, kw_only=True)
    inline_message_id: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    data: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    game_short_name: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    
    @property
    def chat_type(self) -> Optional[str]:
        return self.message.chat.type if self.message else None

    @property
    def chat_id(self) -> Optional[int]:
        return self.message.chat.id if self.message else None

    @property
    def unprefixed_chat_id(self) -> Optional[int]:
        if self.chat_id and self.chat_type:
            return get_unprefixed_chat_id(self.chat_id, self.chat_type)

    @property
    def user_id(self) -> int:
        return self.from_.id

    @property
    def message_id(self) -> Optional[int]:
        return self.message.message_id if self.message else None

    @property
    def payload(self) -> Union[str, int, float, bool, list, None]:
        if self.data:
            _, payload = get_parsed_callback_data(self.data)

            return payload
