# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from datetime import datetime
from typing import Union, Literal, Optional

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.accepted_gift_types import AcceptedGiftTypes
from telebox.bot.types.audio import Audio
from telebox.bot.types.birthdate import Birthdate
from telebox.bot.types.business_intro import BusinessIntro
from telebox.bot.types.business_location import BusinessLocation
from telebox.bot.types.business_opening_hours import BusinessOpeningHours
from telebox.bot.types.chat import Chat
from telebox.bot.types.chat_location import ChatLocation
from telebox.bot.types.chat_permissions import ChatPermissions
from telebox.bot.types.chat_photo import ChatPhoto
from telebox.bot.types.message import Message
from telebox.bot.types.reaction_type import ReactionType
from telebox.bot.types.unique_gift_colors import UniqueGiftColors
from telebox.bot.types.user_rating import UserRating
from telebox.bot.utils.links import get_username_link
from telebox.bot.utils.users import get_full_name
from telebox.utils.unset import Unset


@define(repr=False)
class ChatFullInfo(Type):
    id: int = field()
    type: str = field()
    accent_color_id: int = field()
    max_reaction_count: int = field()
    accepted_gift_types: AcceptedGiftTypes = field()
    title: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    username: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    first_name: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    last_name: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    is_forum: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    is_direct_messages: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    photo: Union[ChatPhoto, None, Unset] = field(factory=default_factory, kw_only=True)
    active_usernames: Union[list[str], None, Unset] = field(factory=default_factory, kw_only=True)
    birthdate: Union[Birthdate, None, Unset] = field(factory=default_factory, kw_only=True)
    business_intro: Union[BusinessIntro, None, Unset] = field(factory=default_factory, kw_only=True)
    business_location: Union[BusinessLocation, None, Unset] = field(factory=default_factory, kw_only=True)
    business_opening_hours: Union[BusinessOpeningHours, None, Unset] = field(factory=default_factory, kw_only=True)
    personal_chat: Union[Chat, None, Unset] = field(factory=default_factory, kw_only=True)
    parent_chat: Union[Chat, None, Unset] = field(factory=default_factory, kw_only=True)
    available_reactions: Union[list[ReactionType], None, Unset] = field(factory=default_factory, kw_only=True)
    background_custom_emoji_id: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    profile_accent_color_id: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    profile_background_custom_emoji_id: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    emoji_status_custom_emoji_id: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    emoji_status_expiration_date: Union[datetime, None, Unset] = field(factory=default_factory, kw_only=True)
    bio: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    has_private_forwards: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    has_restricted_voice_and_video_messages: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    join_to_send_messages: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    join_by_request: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    description: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    invite_link: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    pinned_message: Union[Message, None, Unset] = field(factory=default_factory, kw_only=True)
    permissions: Union[ChatPermissions, None, Unset] = field(factory=default_factory, kw_only=True)
    can_send_paid_media: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    slow_mode_delay: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    unrestrict_boost_count: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    message_auto_delete_time: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    has_aggressive_anti_spam_enabled: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    has_hidden_members: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    has_protected_content: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    has_visible_history: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    sticker_set_name: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    can_set_sticker_set: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    custom_emoji_sticker_set_name: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    linked_chat_id: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    location: Union[ChatLocation, None, Unset] = field(factory=default_factory, kw_only=True)
    rating: Union[UserRating, None, Unset] = field(factory=default_factory, kw_only=True)
    first_profile_audio: Union[Audio, None, Unset] = field(factory=default_factory, kw_only=True)
    unique_gift_colors: Union[UniqueGiftColors, None, Unset] = field(factory=default_factory, kw_only=True)
    paid_message_star_count: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    
    @property
    def full_name(self) -> Optional[str]:
        if self.first_name:
            return get_full_name(self.first_name, self.last_name)

    @property
    def link(self) -> Optional[str]:
        if self.username:
            return get_username_link(self.username)
        elif self.invite_link:
            return self.invite_link
