# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from datetime import datetime

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.chat import Chat
from telebox.bot.types.chat_boost_source import ChatBoostSource


@define(repr=False)
class ChatBoostRemoved(Type):
    chat: Chat = field()
    boost_id: str = field()
    remove_date: datetime = field()
    source: ChatBoostSource = field()
