# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.location import Location


@define(repr=False)
class ChatLocation(Type):
    location: Location = field()
    address: str = field()
