# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from datetime import datetime
from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.user import User
from telebox.unset import Unset


@define(repr=False)
class ChatMemberRestricted(Type):
    user: User = field()
    is_member: bool = field()
    can_send_messages: bool = field()
    can_send_audios: bool = field()
    can_send_documents: bool = field()
    can_send_photos: bool = field()
    can_send_videos: bool = field()
    can_send_video_notes: bool = field()
    can_send_voice_notes: bool = field()
    can_send_polls: bool = field()
    can_send_other_messages: bool = field()
    can_add_web_page_previews: bool = field()
    can_edit_tag: bool = field()
    can_change_info: bool = field()
    can_invite_users: bool = field()
    can_pin_messages: bool = field()
    can_manage_topics: bool = field()
    until_date: Union[datetime, None, Unset] = field(factory=default_factory, kw_only=True)
    tag: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    status: Literal["restricted"] = field(default="restricted", kw_only=True)
