# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from datetime import datetime
from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.user import User
from telebox.unset import Unset


@define(repr=False)
class ChatMemberBanned(Type):
    user: User = field()
    until_date: Union[datetime, None, Unset] = field(factory=default_factory, kw_only=True)
    status: Literal["kicked"] = field(default="kicked", kw_only=True)
