# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.user import User
from telebox.bot.utils.types import default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class ChatBoostSourceGiveaway(Type):
    giveaway_message_id: int = field()
    user: Union[User, None, Unset] = field(factory=default_factory, kw_only=True)
    prize_star_count: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    is_unclaimed: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    source: Literal["giveaway"] = field(default="giveaway", kw_only=True)
