# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union, Literal, Optional

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.utils.links import get_username_link
from telebox.bot.utils.users import get_full_name
from telebox.unset import Unset


@define(repr=False)
class Chat(Type):
    id: int = field()
    type: str = field()
    title: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    username: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    first_name: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    last_name: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    is_forum: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    is_direct_messages: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    
    @property
    def full_name(self) -> Optional[str]:
        if self.first_name:
            return get_full_name(self.first_name, self.last_name)

    @property
    def link(self) -> Optional[str]:
        if self.username:
            return get_username_link(self.username)
