# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from datetime import datetime
from typing import Union

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.chat import Chat
from telebox.bot.types.chat_invite_link import ChatInviteLink
from telebox.bot.types.user import User
from telebox.bot.utils.ids import get_unprefixed_chat_id
from telebox.bot.utils.types import default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class ChatJoinRequest(Type):
    chat: Chat = field()
    from_: User = field()
    user_chat_id: int = field()
    date: datetime = field()
    bio: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    invite_link: Union[ChatInviteLink, None, Unset] = field(factory=default_factory, kw_only=True)
    
    @property
    def chat_type(self) -> str:
        return self.chat.type

    @property
    def chat_id(self) -> int:
        return self.chat.id

    @property
    def unprefixed_chat_id(self) -> int:
        return get_unprefixed_chat_id(self.chat.id, self.chat.type)

    @property
    def user_id(self) -> int:
        return self.from_.id
