# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.user import User
from telebox.unset import Unset


@define(repr=False)
class ChatMemberAdministrator(Type):
    user: User = field()
    can_be_edited: bool = field()
    is_anonymous: bool = field()
    can_manage_chat: bool = field()
    can_delete_messages: bool = field()
    can_manage_video_chats: bool = field()
    can_restrict_members: bool = field()
    can_promote_members: bool = field()
    can_change_info: bool = field()
    can_invite_users: bool = field()
    can_post_stories: bool = field()
    can_edit_stories: bool = field()
    can_delete_stories: bool = field()
    can_post_messages: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    can_edit_messages: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    can_pin_messages: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    can_manage_topics: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    can_manage_direct_messages: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    can_manage_tags: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    custom_title: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    status: Literal["administrator"] = field(default="administrator", kw_only=True)
