# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.background_type import BackgroundType


@define(repr=False)
class ChatBackground(Type):
    type: BackgroundType = field()
