# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class ChatPermissions(Type):
    can_send_messages: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    can_send_audios: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    can_send_documents: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    can_send_photos: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    can_send_videos: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    can_send_video_notes: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    can_send_voice_notes: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    can_send_polls: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    can_send_other_messages: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    can_add_web_page_previews: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    can_edit_tag: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    can_change_info: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    can_invite_users: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    can_pin_messages: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    can_manage_topics: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
