# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.chat import Chat
from telebox.bot.types.chat_boost import ChatBoost


@define(repr=False)
class ChatBoostUpdated(Type):
    chat: Chat = field()
    boost: ChatBoost = field()
