# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from telebox.bot.types.chat_boost_source_gift_code import ChatBoostSourceGiftCode
from telebox.bot.types.chat_boost_source_giveaway import ChatBoostSourceGiveaway
from telebox.bot.types.chat_boost_source_premium import ChatBoostSourcePremium


ChatBoostSource = Union[
    ChatBoostSourcePremium,
    ChatBoostSourceGiftCode,
    ChatBoostSourceGiveaway
]
