# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from datetime import datetime
from typing import Union

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.user import User
from telebox.bot.utils.types import default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class ChatInviteLink(Type):
    invite_link: str = field()
    creator: User = field()
    creates_join_request: bool = field()
    is_primary: bool = field()
    is_revoked: bool = field()
    name: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    expire_date: Union[datetime, None, Unset] = field(factory=default_factory, kw_only=True)
    member_limit: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    pending_join_request_count: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    subscription_period: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    subscription_price: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
