# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.user import User
from telebox.unset import Unset


@define(repr=False)
class ChatOwnerLeft(Type):
    new_owner: Union[User, None, Unset] = field(factory=default_factory, kw_only=True)
