# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.user import User
from telebox.unset import Unset


@define(repr=False)
class ChatMemberOwner(Type):
    user: User = field()
    is_anonymous: bool = field()
    custom_title: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    status: Literal["creator"] = field(default="creator", kw_only=True)
