# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.photo_size import PhotoSize
from telebox.bot.utils.types import default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class ChatShared(Type):
    request_id: int = field()
    chat_id: int = field()
    title: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    username: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    photo: Union[list[PhotoSize], None, Unset] = field(factory=default_factory, kw_only=True)
