# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Literal

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.user import User


@define(repr=False)
class ChatBoostSourcePremium(Type):
    user: User = field()
    source: Literal["premium"] = field(default="premium", kw_only=True)
