# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Optional

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.chat import Chat
from telebox.bot.types.chat_boost import ChatBoost
from telebox.bot.utils.ids import get_unprefixed_chat_id


@define(repr=False)
class ChatBoostUpdated(Type):
    chat: Chat = field()
    boost: ChatBoost = field()
    
    @property
    def chat_type(self) -> str:
        return self.chat.type

    @property
    def chat_id(self) -> int:
        return self.chat.id

    @property
    def unprefixed_chat_id(self) -> int:
        return get_unprefixed_chat_id(self.chat.id, self.chat.type)

    @property
    def user_id(self) -> Optional[int]:
        if self.boost.source.user:
            return self.boost.source.user.id
