# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from datetime import datetime

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.chat_boost_source import ChatBoostSource


@define(repr=False)
class ChatBoost(Type):
    boost_id: str = field()
    add_date: datetime = field()
    expiration_date: datetime = field()
    source: ChatBoostSource = field()
