# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from datetime import datetime
from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.chat import Chat
from telebox.bot.types.chat_invite_link import ChatInviteLink
from telebox.bot.types.chat_member import ChatMember
from telebox.bot.types.user import User
from telebox.bot.utils.ids import get_unprefixed_chat_id
from telebox.utils.unset import Unset


@define(repr=False)
class ChatMemberUpdated(Type):
    chat: Chat = field()
    from_: User = field()
    date: datetime = field()
    old_chat_member: ChatMember = field()
    new_chat_member: ChatMember = field()
    invite_link: Union[ChatInviteLink, None, Unset] = field(factory=default_factory, kw_only=True)
    via_join_request: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    via_chat_folder_invite_link: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    
    @property
    def chat_type(self) -> str:
        return self.chat.type

    @property
    def chat_id(self) -> int:
        return self.chat.id

    @property
    def unprefixed_chat_id(self) -> int:
        return get_unprefixed_chat_id(self.chat.id, self.chat.type)

    @property
    def user_id(self) -> int:
        return self.from_.id
