# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class ChatPhoto(Type):
    small_file_id: str = field()
    small_file_unique_id: str = field()
    big_file_id: str = field()
    big_file_unique_id: str = field()
