# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.message import Message
from telebox.bot.utils.types import default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class ChecklistTasksDone(Type):
    checklist_message: Union[Message, None, Unset] = field(factory=default_factory, kw_only=True)
    marked_as_done_task_ids: Union[list[int], None, Unset] = field(factory=default_factory, kw_only=True)
    marked_as_not_done_task_ids: Union[list[int], None, Unset] = field(factory=default_factory, kw_only=True)
