# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.checklist_task import ChecklistTask
from telebox.bot.types.message_entity import MessageEntity
from telebox.bot.utils.types import default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class Checklist(Type):
    title: str = field()
    tasks: list[ChecklistTask] = field()
    title_entities: Union[list[MessageEntity], None, Unset] = field(factory=default_factory, kw_only=True)
    others_can_add_tasks: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    others_can_mark_tasks_as_done: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
