# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from datetime import datetime
from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.chat import Chat
from telebox.bot.types.message_entity import MessageEntity
from telebox.bot.types.user import User
from telebox.unset import Unset


@define(repr=False)
class ChecklistTask(Type):
    id: int = field()
    text: str = field()
    text_entities: Union[list[MessageEntity], None, Unset] = field(factory=default_factory, kw_only=True)
    completed_by_user: Union[User, None, Unset] = field(factory=default_factory, kw_only=True)
    completed_by_chat: Union[Chat, None, Unset] = field(factory=default_factory, kw_only=True)
    completion_date: Union[datetime, None, Unset] = field(factory=default_factory, kw_only=True)
