# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.checklist_task import ChecklistTask
from telebox.bot.types.message import Message
from telebox.bot.utils.types import default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class ChecklistTasksAdded(Type):
    tasks: list[ChecklistTask] = field()
    checklist_message: Union[Message, None, Unset] = field(factory=default_factory, kw_only=True)
