# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.utils.users import get_full_name
from telebox.utils.unset import Unset


@define(repr=False)
class Contact(Type):
    phone_number: str = field()
    first_name: str = field()
    last_name: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    user_id: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    vcard: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    
    @property
    def full_name(self) -> str:
        return get_full_name(self.first_name, self.last_name)
