# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.user import User
from telebox.bot.utils.types import default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class DirectMessagesTopic(Type):
    topic_id: int = field()
    user: Union[User, None, Unset] = field(factory=default_factory, kw_only=True)
