# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.unset import Unset


@define(repr=False)
class DirectMessagePriceChanged(Type):
    are_direct_messages_enabled: bool = field()
    direct_message_star_count: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
