# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.passport_file import PassportFile
from telebox.bot.utils.types import default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class EncryptedPassportElement(Type):
    type: str = field()
    hash: str = field()
    data: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    phone_number: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    email: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    files: Union[list[PassportFile], None, Unset] = field(factory=default_factory, kw_only=True)
    front_side: Union[PassportFile, None, Unset] = field(factory=default_factory, kw_only=True)
    reverse_side: Union[PassportFile, None, Unset] = field(factory=default_factory, kw_only=True)
    selfie: Union[PassportFile, None, Unset] = field(factory=default_factory, kw_only=True)
    translation: Union[list[PassportFile], None, Unset] = field(factory=default_factory, kw_only=True)
