# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.animation import Animation
from telebox.bot.types.audio import Audio
from telebox.bot.types.chat import Chat
from telebox.bot.types.checklist import Checklist
from telebox.bot.types.contact import Contact
from telebox.bot.types.dice import Dice
from telebox.bot.types.document import Document
from telebox.bot.types.game import Game
from telebox.bot.types.giveaway import Giveaway
from telebox.bot.types.giveaway_winners import GiveawayWinners
from telebox.bot.types.invoice import Invoice
from telebox.bot.types.link_preview_options import LinkPreviewOptions
from telebox.bot.types.live_photo import LivePhoto
from telebox.bot.types.location import Location
from telebox.bot.types.message_origin import MessageOrigin
from telebox.bot.types.paid_media_info import PaidMediaInfo
from telebox.bot.types.photo_size import PhotoSize
from telebox.bot.types.poll import Poll
from telebox.bot.types.sticker import Sticker
from telebox.bot.types.story import Story
from telebox.bot.types.venue import Venue
from telebox.bot.types.video import Video
from telebox.bot.types.video_note import VideoNote
from telebox.bot.types.voice import Voice
from telebox.unset import Unset


@define(repr=False)
class ExternalReplyInfo(Type):
    origin: MessageOrigin = field()
    chat: Union[Chat, None, Unset] = field(factory=default_factory, kw_only=True)
    message_id: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    link_preview_options: Union[LinkPreviewOptions, None, Unset] = field(factory=default_factory, kw_only=True)
    animation: Union[Animation, None, Unset] = field(factory=default_factory, kw_only=True)
    audio: Union[Audio, None, Unset] = field(factory=default_factory, kw_only=True)
    document: Union[Document, None, Unset] = field(factory=default_factory, kw_only=True)
    live_photo: Union[LivePhoto, None, Unset] = field(factory=default_factory, kw_only=True)
    paid_media: Union[PaidMediaInfo, None, Unset] = field(factory=default_factory, kw_only=True)
    photo: Union[list[PhotoSize], None, Unset] = field(factory=default_factory, kw_only=True)
    sticker: Union[Sticker, None, Unset] = field(factory=default_factory, kw_only=True)
    story: Union[Story, None, Unset] = field(factory=default_factory, kw_only=True)
    video: Union[Video, None, Unset] = field(factory=default_factory, kw_only=True)
    video_note: Union[VideoNote, None, Unset] = field(factory=default_factory, kw_only=True)
    voice: Union[Voice, None, Unset] = field(factory=default_factory, kw_only=True)
    has_media_spoiler: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    checklist: Union[Checklist, None, Unset] = field(factory=default_factory, kw_only=True)
    contact: Union[Contact, None, Unset] = field(factory=default_factory, kw_only=True)
    dice: Union[Dice, None, Unset] = field(factory=default_factory, kw_only=True)
    game: Union[Game, None, Unset] = field(factory=default_factory, kw_only=True)
    giveaway: Union[Giveaway, None, Unset] = field(factory=default_factory, kw_only=True)
    giveaway_winners: Union[GiveawayWinners, None, Unset] = field(factory=default_factory, kw_only=True)
    invoice: Union[Invoice, None, Unset] = field(factory=default_factory, kw_only=True)
    location: Union[Location, None, Unset] = field(factory=default_factory, kw_only=True)
    poll: Union[Poll, None, Unset] = field(factory=default_factory, kw_only=True)
    venue: Union[Venue, None, Unset] = field(factory=default_factory, kw_only=True)
