# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class ForumTopic(Type):
    message_thread_id: int = field()
    name: str = field()
    icon_color: int = field()
    icon_custom_emoji_id: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
