# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.animation import Animation
from telebox.bot.types.message_entity import MessageEntity
from telebox.bot.types.photo_size import PhotoSize
from telebox.unset import Unset


@define(repr=False)
class Game(Type):
    title: str = field()
    description: str = field()
    photo: list[PhotoSize] = field()
    text: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    text_entities: Union[list[MessageEntity], None, Unset] = field(factory=default_factory, kw_only=True)
    animation: Union[Animation, None, Unset] = field(factory=default_factory, kw_only=True)
