# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from attrs import define

from telebox.bot.type import Type


@define(repr=False)
class GeneralForumTopicUnhidden(Type):
    pass
