# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.chat import Chat
from telebox.bot.types.gift_background import GiftBackground
from telebox.bot.types.sticker import Sticker
from telebox.unset import Unset


@define(repr=False)
class Gift(Type):
    id: str = field()
    sticker: Sticker = field()
    star_count: int = field()
    upgrade_star_count: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    is_premium: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    has_colors: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    total_count: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    remaining_count: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    personal_total_count: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    personal_remaining_count: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    background: Union[GiftBackground, None, Unset] = field(factory=default_factory, kw_only=True)
    unique_gift_variant_count: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    publisher_chat: Union[Chat, None, Unset] = field(factory=default_factory, kw_only=True)
