# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.chat import Chat
from telebox.bot.types.sticker import Sticker
from telebox.utils.unset import Unset


@define(repr=False)
class Gift(Type):
    id: str = field()
    sticker: Sticker = field()
    star_count: int = field()
    upgrade_star_count: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    total_count: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    remaining_count: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    publisher_chat: Union[Chat, None, Unset] = field(factory=default_factory, kw_only=True)
