# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.gift import Gift


@define(repr=False)
class Gifts(Type):
    gifts: list[Gift] = field()
