# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.gift import Gift
from telebox.bot.types.message_entity import MessageEntity
from telebox.utils.unset import Unset


@define(repr=False)
class GiftInfo(Type):
    gift: Gift = field()
    owned_gift_id: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    convert_star_count: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    prepaid_upgrade_star_count: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    can_be_upgraded: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    text: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    entities: Union[list[MessageEntity], None, Unset] = field(factory=default_factory, kw_only=True)
    is_private: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
