# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.message import Message
from telebox.unset import Unset


@define(repr=False)
class GiveawayCompleted(Type):
    winner_count: int = field()
    unclaimed_prize_count: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    giveaway_message: Union[Message, None, Unset] = field(factory=default_factory, kw_only=True)
    is_star_giveaway: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
