# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from datetime import datetime
from typing import Literal, Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.chat import Chat
from telebox.unset import Unset


@define(repr=False)
class Giveaway(Type):
    chats: list[Chat] = field()
    winners_selection_date: datetime = field()
    winner_count: int = field()
    only_new_members: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    has_public_winners: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    prize_description: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    country_codes: Union[list[str], None, Unset] = field(factory=default_factory, kw_only=True)
    prize_star_count: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    premium_subscription_month_count: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
