# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from datetime import datetime
from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.chat import Chat
from telebox.bot.types.user import User
from telebox.bot.utils.types import default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class GiveawayWinners(Type):
    chat: Chat = field()
    giveaway_message_id: int = field()
    winners_selection_date: datetime = field()
    winner_count: int = field()
    winners: list[User] = field()
    additional_chat_count: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    prize_star_count: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    premium_subscription_month_count: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    unclaimed_prize_count: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    only_new_members: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    was_refunded: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    prize_description: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
