# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from datetime import datetime

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.chat import Chat


@define(repr=False)
class InaccessibleMessage(Type):
    chat: Chat = field()
    message_id: int = field()
    date: datetime = field()
