# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.location import Location
from telebox.bot.types.user import User
from telebox.bot.utils.types import default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class InlineQuery(Type):
    id: str = field()
    from_: User = field()
    query: str = field()
    offset: str = field()
    chat_type: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    location: Union[Location, None, Unset] = field(factory=default_factory, kw_only=True)
    
    @property
    def user_id(self) -> int:
        return self.from_.id
