# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.callback_game import CallbackGame
from telebox.bot.types.copy_text_button import CopyTextButton
from telebox.bot.types.login_url import LoginUrl
from telebox.bot.types.switch_inline_query_chosen_chat import SwitchInlineQueryChosenChat
from telebox.bot.types.web_app_info import WebAppInfo
from telebox.utils.unset import Unset


@define(repr=False)
class InlineKeyboardButton(Type):
    text: str = field()
    icon_custom_emoji_id: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    style: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    url: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    callback_data: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    web_app: Union[WebAppInfo, None, Unset] = field(factory=default_factory, kw_only=True)
    login_url: Union[LoginUrl, None, Unset] = field(factory=default_factory, kw_only=True)
    switch_inline_query: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    switch_inline_query_current_chat: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    switch_inline_query_chosen_chat: Union[SwitchInlineQueryChosenChat, None, Unset] = field(factory=default_factory, kw_only=True)
    copy_text: Union[CopyTextButton, None, Unset] = field(factory=default_factory, kw_only=True)
    callback_game: Union[CallbackGame, None, Unset] = field(factory=default_factory, kw_only=True)
    pay: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
