# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Optional

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.inline_keyboard_button import InlineKeyboardButton


@define(repr=False)
class InlineKeyboardMarkup(Type):
    inline_keyboard: list[list[InlineKeyboardButton]] = field()
    
    @property
    def rows(self) -> int:
        return len(self.inline_keyboard)

    def add_row(self, *buttons: InlineKeyboardButton, index: Optional[int] = None) -> None:
        if index is None:
            self.inline_keyboard.append(list(buttons))
        else:
            self.inline_keyboard.insert(index, list(buttons))

    def get_row_length(self, *, index: int = -1) -> int:
        return len(self.inline_keyboard[index])

    def add_in_row(self, button: InlineKeyboardButton, *, index: int = -1) -> None:
        self.inline_keyboard[index].append(button)
