# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from telebox.bot.types.input_media_animation import InputMediaAnimation
from telebox.bot.types.input_media_live_photo import InputMediaLivePhoto
from telebox.bot.types.input_media_location import InputMediaLocation
from telebox.bot.types.input_media_photo import InputMediaPhoto
from telebox.bot.types.input_media_sticker import InputMediaSticker
from telebox.bot.types.input_media_venue import InputMediaVenue
from telebox.bot.types.input_media_video import InputMediaVideo


InputPollOptionMedia = Union[
    InputMediaAnimation,
    InputMediaLivePhoto,
    InputMediaLocation,
    InputMediaPhoto,
    InputMediaSticker,
    InputMediaVenue,
    InputMediaVideo
]
