# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.message_entity import MessageEntity
from telebox.utils.unset import Unset


@define(repr=False)
class InputPollOption(Type):
    text: str = field()
    text_parse_mode: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    text_entities: Union[list[MessageEntity], None, Unset] = field(factory=default_factory, kw_only=True)
