# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.input_file import InputFile
from telebox.bot.utils.types import default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class InputStoryContentVideo(Type):
    video: Union[str, InputFile] = field()
    duration: Union[float, None, Unset] = field(factory=default_factory, kw_only=True)
    cover_frame_timestamp: Union[float, None, Unset] = field(factory=default_factory, kw_only=True)
    is_animation: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    type: Literal["video"] = field(default="video", kw_only=True)
