# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.input_file import InputFile
from telebox.bot.types.message_entity import MessageEntity
from telebox.bot.utils.types import default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class InputMediaAudio(Type):
    media: Union[str, InputFile] = field()
    thumbnail: Union[str, InputFile, None, Unset] = field(factory=default_factory, kw_only=True)
    caption: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    parse_mode: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    caption_entities: Union[list[MessageEntity], None, Unset] = field(factory=default_factory, kw_only=True)
    duration: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    performer: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    title: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    type: Literal["audio"] = field(default="audio", kw_only=True)
