# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.unset import Unset


@define(repr=False)
class InputMediaLocation(Type):
    latitude: float = field()
    longitude: float = field()
    horizontal_accuracy: Union[float, None, Unset] = field(factory=default_factory, kw_only=True)
    type: Literal["location"] = field(default="location", kw_only=True)
