# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.labeled_price import LabeledPrice
from telebox.unset import Unset


@define(repr=False)
class InputInvoiceMessageContent(Type):
    title: str = field()
    description: str = field()
    payload: str = field()
    currency: str = field()
    prices: list[LabeledPrice] = field()
    provider_token: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    max_tip_amount: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    suggested_tip_amounts: Union[list[int], None, Unset] = field(factory=default_factory, kw_only=True)
    provider_data: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    photo_url: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    photo_size: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    photo_width: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    photo_height: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    need_name: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    need_phone_number: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    need_email: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    need_shipping_address: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    send_phone_number_to_provider: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    send_email_to_provider: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    is_flexible: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
