# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.input_file import InputFile
from telebox.unset import Unset


@define(repr=False)
class InputProfilePhotoAnimated(Type):
    animation: Union[str, InputFile] = field()
    main_frame_timestamp: Union[float, None, Unset] = field(factory=default_factory, kw_only=True)
    type: Literal["animated"] = field(default="animated", kw_only=True)
