# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.link_preview_options import LinkPreviewOptions
from telebox.bot.types.message_entity import MessageEntity
from telebox.bot.utils.types import default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class InputTextMessageContent(Type):
    message_text: str = field()
    parse_mode: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    entities: Union[list[MessageEntity], None, Unset] = field(factory=default_factory, kw_only=True)
    link_preview_options: Union[LinkPreviewOptions, None, Unset] = field(factory=default_factory, kw_only=True)
