# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from telebox.bot.types.input_contact_message_content import InputContactMessageContent
from telebox.bot.types.input_invoice_message_content import InputInvoiceMessageContent
from telebox.bot.types.input_location_message_content import InputLocationMessageContent
from telebox.bot.types.input_text_message_content import InputTextMessageContent
from telebox.bot.types.input_venue_message_content import InputVenueMessageContent


InputMessageContent = Union[
    InputTextMessageContent,
    InputLocationMessageContent,
    InputVenueMessageContent,
    InputContactMessageContent,
    InputInvoiceMessageContent
]
