# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from telebox.bot.types.input_paid_media_photo import InputPaidMediaPhoto
from telebox.bot.types.input_paid_media_video import InputPaidMediaVideo


InputPaidMedia = Union[
    InputPaidMediaPhoto,
    InputPaidMediaVideo
]
