# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from telebox.bot.types.input_profile_photo_animated import InputProfilePhotoAnimated
from telebox.bot.types.input_profile_photo_static import InputProfilePhotoStatic


InputProfilePhoto = Union[
    InputProfilePhotoStatic,
    InputProfilePhotoAnimated
]
