# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.input_file import InputFile


@define(repr=False)
class InputProfilePhotoStatic(Type):
    photo: Union[str, InputFile] = field()
    type: Literal["static"] = field(default="static", kw_only=True)
