# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.input_file import InputFile
from telebox.bot.types.message_entity import MessageEntity
from telebox.unset import Unset


@define(repr=False)
class InputMediaDocument(Type):
    media: Union[str, InputFile] = field()
    thumbnail: Union[str, InputFile, None, Unset] = field(factory=default_factory, kw_only=True)
    caption: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    parse_mode: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    caption_entities: Union[list[MessageEntity], None, Unset] = field(factory=default_factory, kw_only=True)
    disable_content_type_detection: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    type: Literal["document"] = field(default="document", kw_only=True)
