# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from telebox.bot.types.input_media_animation import InputMediaAnimation
from telebox.bot.types.input_media_audio import InputMediaAudio
from telebox.bot.types.input_media_document import InputMediaDocument
from telebox.bot.types.input_media_photo import InputMediaPhoto
from telebox.bot.types.input_media_video import InputMediaVideo


InputMedia = Union[
    InputMediaAnimation,
    InputMediaDocument,
    InputMediaAudio,
    InputMediaPhoto,
    InputMediaVideo
]
