# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.utils.types import default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class InputLocationMessageContent(Type):
    latitude: float = field()
    longitude: float = field()
    horizontal_accuracy: Union[float, None, Unset] = field(factory=default_factory, kw_only=True)
    live_period: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    heading: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    proximity_alert_radius: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
