# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.input_file import InputFile
from telebox.bot.types.mask_position import MaskPosition
from telebox.bot.utils.types import default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class InputSticker(Type):
    sticker: Union[str, InputFile] = field()
    format: str = field()
    emoji_list: list[str] = field()
    mask_position: Union[MaskPosition, None, Unset] = field(factory=default_factory, kw_only=True)
    keywords: Union[list[str], None, Unset] = field(factory=default_factory, kw_only=True)
