# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from telebox.bot.types.input_story_content_photo import InputStoryContentPhoto
from telebox.bot.types.input_story_content_video import InputStoryContentVideo


InputStoryContent = Union[
    InputStoryContentPhoto,
    InputStoryContentVideo
]
