# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.input_checklist_task import InputChecklistTask
from telebox.bot.types.message_entity import MessageEntity
from telebox.bot.utils.types import default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class InputChecklist(Type):
    title: str = field()
    tasks: list[InputChecklistTask] = field()
    parse_mode: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    title_entities: Union[list[MessageEntity], None, Unset] = field(factory=default_factory, kw_only=True)
    others_can_add_tasks: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    others_can_mark_tasks_as_done: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
