# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class Invoice(Type):
    title: str = field()
    description: str = field()
    start_parameter: str = field()
    currency: str = field()
    total_amount: int = field()
