# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.utils.types import default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class KeyboardButtonRequestUsers(Type):
    request_id: int = field()
    user_is_bot: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    user_is_premium: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    max_quantity: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    request_name: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    request_username: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    request_photo: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
