# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.chat_administrator_rights import ChatAdministratorRights
from telebox.unset import Unset


@define(repr=False)
class KeyboardButtonRequestChat(Type):
    request_id: int = field()
    chat_is_channel: bool = field()
    chat_is_forum: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    chat_has_username: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    chat_is_created: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    user_administrator_rights: Union[ChatAdministratorRights, None, Unset] = field(factory=default_factory, kw_only=True)
    bot_administrator_rights: Union[ChatAdministratorRights, None, Unset] = field(factory=default_factory, kw_only=True)
    bot_is_member: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    request_title: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    request_username: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    request_photo: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
