# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.unset import Unset


@define(repr=False)
class LinkPreviewOptions(Type):
    is_disabled: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    url: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    prefer_small_media: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    prefer_large_media: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    show_above_text: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
