# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class LocationAddress(Type):
    country_code: str = field()
    state: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    city: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    street: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
