# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class LoginUrl(Type):
    url: str = field()
    forward_text: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    bot_username: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    request_write_access: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
