# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.user import User


@define(repr=False)
class ManagedBotUpdated(Type):
    user: User = field()
    bot: User = field()
