# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class MaskPosition(Type):
    point: str = field()
    x_shift: float = field()
    y_shift: float = field()
    scale: float = field()
