# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from telebox.bot.types.inaccessible_message import InaccessibleMessage
from telebox.bot.types.message import Message


MaybeInaccessibleMessage = Union[
    Message,
    InaccessibleMessage
]
