# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Literal

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class MenuButtonCommands(Type):
    type: Literal["commands"] = field(default="commands", kw_only=True)
