# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from telebox.bot.types.menu_button_commands import MenuButtonCommands
from telebox.bot.types.menu_button_default import MenuButtonDefault
from telebox.bot.types.menu_button_web_app import MenuButtonWebApp


MenuButton = Union[
    MenuButtonCommands,
    MenuButtonWebApp,
    MenuButtonDefault
]
