# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Literal

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.web_app_info import WebAppInfo


@define(repr=False)
class MenuButtonWebApp(Type):
    text: str = field()
    web_app: WebAppInfo = field()
    type: Literal["web_app"] = field(default="web_app", kw_only=True)
