# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from datetime import datetime
from typing import Literal

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class MessageOriginHiddenUser(Type):
    date: datetime = field()
    sender_user_name: str = field()
    type: Literal["hidden_user"] = field(default="hidden_user", kw_only=True)
