# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from datetime import datetime
from typing import Union, Literal, Optional, TYPE_CHECKING

from attrs import field, define

from telebox.bot.enums.message_type import MessageType
from telebox.bot.type import Type, default_factory
from telebox.bot.types.animation import Animation
from telebox.bot.types.audio import Audio
from telebox.bot.types.chat import Chat
from telebox.bot.types.chat_background import ChatBackground
from telebox.bot.types.chat_boost_added import ChatBoostAdded
from telebox.bot.types.chat_owner_changed import ChatOwnerChanged
from telebox.bot.types.chat_owner_left import ChatOwnerLeft
from telebox.bot.types.chat_shared import ChatShared
from telebox.bot.types.checklist import Checklist
from telebox.bot.types.contact import Contact
from telebox.bot.types.dice import Dice
from telebox.bot.types.direct_message_price_changed import DirectMessagePriceChanged
from telebox.bot.types.direct_messages_topic import DirectMessagesTopic
from telebox.bot.types.document import Document
from telebox.bot.types.external_reply_info import ExternalReplyInfo
from telebox.bot.types.forum_topic_closed import ForumTopicClosed
from telebox.bot.types.forum_topic_created import ForumTopicCreated
from telebox.bot.types.forum_topic_edited import ForumTopicEdited
from telebox.bot.types.forum_topic_reopened import ForumTopicReopened
from telebox.bot.types.game import Game
from telebox.bot.types.general_forum_topic_hidden import GeneralForumTopicHidden
from telebox.bot.types.general_forum_topic_unhidden import GeneralForumTopicUnhidden
from telebox.bot.types.gift_info import GiftInfo
from telebox.bot.types.giveaway import Giveaway
from telebox.bot.types.giveaway_created import GiveawayCreated
from telebox.bot.types.giveaway_winners import GiveawayWinners
from telebox.bot.types.inline_keyboard_markup import InlineKeyboardMarkup
from telebox.bot.types.invoice import Invoice
from telebox.bot.types.link_preview_options import LinkPreviewOptions
from telebox.bot.types.location import Location
from telebox.bot.types.message_auto_delete_timer_changed import MessageAutoDeleteTimerChanged
from telebox.bot.types.message_entity import MessageEntity
from telebox.bot.types.message_origin import MessageOrigin
from telebox.bot.types.paid_media_info import PaidMediaInfo
from telebox.bot.types.paid_message_price_changed import PaidMessagePriceChanged
from telebox.bot.types.passport_data import PassportData
from telebox.bot.types.photo_size import PhotoSize
from telebox.bot.types.poll import Poll
from telebox.bot.types.proximity_alert_triggered import ProximityAlertTriggered
from telebox.bot.types.refunded_payment import RefundedPayment
from telebox.bot.types.sticker import Sticker
from telebox.bot.types.story import Story
from telebox.bot.types.successful_payment import SuccessfulPayment
from telebox.bot.types.suggested_post_info import SuggestedPostInfo
from telebox.bot.types.text_quote import TextQuote
from telebox.bot.types.unique_gift_info import UniqueGiftInfo
from telebox.bot.types.user import User
from telebox.bot.types.users_shared import UsersShared
from telebox.bot.types.venue import Venue
from telebox.bot.types.video import Video
from telebox.bot.types.video_chat_ended import VideoChatEnded
from telebox.bot.types.video_chat_participants_invited import VideoChatParticipantsInvited
from telebox.bot.types.video_chat_scheduled import VideoChatScheduled
from telebox.bot.types.video_chat_started import VideoChatStarted
from telebox.bot.types.video_note import VideoNote
from telebox.bot.types.voice import Voice
from telebox.bot.types.web_app_data import WebAppData
from telebox.bot.types.write_access_allowed import WriteAccessAllowed
from telebox.bot.utils.ids import get_unprefixed_chat_id
from telebox.bot.utils.links import get_message_public_link, get_message_private_link
from telebox.bot.utils.texts import get_text_formatter
from telebox.utils.text import get_text_with_surrogates, get_text_without_surrogates
from telebox.utils.unset import Unset
if TYPE_CHECKING:
    from telebox.bot.types.checklist_tasks_added import ChecklistTasksAdded
    from telebox.bot.types.checklist_tasks_done import ChecklistTasksDone
    from telebox.bot.types.giveaway_completed import GiveawayCompleted
    from telebox.bot.types.maybe_inaccessible_message import MaybeInaccessibleMessage
    from telebox.bot.types.suggested_post_approval_failed import SuggestedPostApprovalFailed
    from telebox.bot.types.suggested_post_approved import SuggestedPostApproved
    from telebox.bot.types.suggested_post_declined import SuggestedPostDeclined
    from telebox.bot.types.suggested_post_paid import SuggestedPostPaid
    from telebox.bot.types.suggested_post_refunded import SuggestedPostRefunded


@define(repr=False)
class Message(Type):
    message_id: int = field()
    date: datetime = field()
    chat: Chat = field()
    message_thread_id: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    direct_messages_topic: Union[DirectMessagesTopic, None, Unset] = field(factory=default_factory, kw_only=True)
    from_: Union[User, None, Unset] = field(factory=default_factory, kw_only=True)
    sender_chat: Union[Chat, None, Unset] = field(factory=default_factory, kw_only=True)
    sender_boost_count: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    sender_business_bot: Union[User, None, Unset] = field(factory=default_factory, kw_only=True)
    sender_tag: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    business_connection_id: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    forward_origin: Union[MessageOrigin, None, Unset] = field(factory=default_factory, kw_only=True)
    is_topic_message: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    is_automatic_forward: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    reply_to_message: Union["Message", None, Unset] = field(factory=default_factory, kw_only=True)
    external_reply: Union[ExternalReplyInfo, None, Unset] = field(factory=default_factory, kw_only=True)
    quote: Union[TextQuote, None, Unset] = field(factory=default_factory, kw_only=True)
    reply_to_story: Union[Story, None, Unset] = field(factory=default_factory, kw_only=True)
    reply_to_checklist_task_id: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    via_bot: Union[User, None, Unset] = field(factory=default_factory, kw_only=True)
    edit_date: Union[datetime, None, Unset] = field(factory=default_factory, kw_only=True)
    has_protected_content: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    is_from_offline: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    is_paid_post: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    media_group_id: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    author_signature: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    paid_star_count: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    text: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    entities: Union[list[MessageEntity], None, Unset] = field(factory=default_factory, kw_only=True)
    link_preview_options: Union[LinkPreviewOptions, None, Unset] = field(factory=default_factory, kw_only=True)
    suggested_post_info: Union[SuggestedPostInfo, None, Unset] = field(factory=default_factory, kw_only=True)
    effect_id: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    animation: Union[Animation, None, Unset] = field(factory=default_factory, kw_only=True)
    audio: Union[Audio, None, Unset] = field(factory=default_factory, kw_only=True)
    document: Union[Document, None, Unset] = field(factory=default_factory, kw_only=True)
    paid_media: Union[PaidMediaInfo, None, Unset] = field(factory=default_factory, kw_only=True)
    photo: Union[list[PhotoSize], None, Unset] = field(factory=default_factory, kw_only=True)
    sticker: Union[Sticker, None, Unset] = field(factory=default_factory, kw_only=True)
    story: Union[Story, None, Unset] = field(factory=default_factory, kw_only=True)
    video: Union[Video, None, Unset] = field(factory=default_factory, kw_only=True)
    video_note: Union[VideoNote, None, Unset] = field(factory=default_factory, kw_only=True)
    voice: Union[Voice, None, Unset] = field(factory=default_factory, kw_only=True)
    caption: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    caption_entities: Union[list[MessageEntity], None, Unset] = field(factory=default_factory, kw_only=True)
    show_caption_above_media: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    has_media_spoiler: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    checklist: Union[Checklist, None, Unset] = field(factory=default_factory, kw_only=True)
    contact: Union[Contact, None, Unset] = field(factory=default_factory, kw_only=True)
    dice: Union[Dice, None, Unset] = field(factory=default_factory, kw_only=True)
    game: Union[Game, None, Unset] = field(factory=default_factory, kw_only=True)
    poll: Union[Poll, None, Unset] = field(factory=default_factory, kw_only=True)
    venue: Union[Venue, None, Unset] = field(factory=default_factory, kw_only=True)
    location: Union[Location, None, Unset] = field(factory=default_factory, kw_only=True)
    new_chat_members: Union[list[User], None, Unset] = field(factory=default_factory, kw_only=True)
    left_chat_member: Union[User, None, Unset] = field(factory=default_factory, kw_only=True)
    chat_owner_left: Union[ChatOwnerLeft, None, Unset] = field(factory=default_factory, kw_only=True)
    chat_owner_changed: Union[ChatOwnerChanged, None, Unset] = field(factory=default_factory, kw_only=True)
    new_chat_title: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    new_chat_photo: Union[list[PhotoSize], None, Unset] = field(factory=default_factory, kw_only=True)
    delete_chat_photo: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    group_chat_created: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    supergroup_chat_created: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    channel_chat_created: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    message_auto_delete_timer_changed: Union[MessageAutoDeleteTimerChanged, None, Unset] = field(factory=default_factory, kw_only=True)
    migrate_to_chat_id: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    migrate_from_chat_id: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    pinned_message: Union["MaybeInaccessibleMessage", None, Unset] = field(factory=default_factory, kw_only=True)
    invoice: Union[Invoice, None, Unset] = field(factory=default_factory, kw_only=True)
    successful_payment: Union[SuccessfulPayment, None, Unset] = field(factory=default_factory, kw_only=True)
    refunded_payment: Union[RefundedPayment, None, Unset] = field(factory=default_factory, kw_only=True)
    users_shared: Union[UsersShared, None, Unset] = field(factory=default_factory, kw_only=True)
    chat_shared: Union[ChatShared, None, Unset] = field(factory=default_factory, kw_only=True)
    gift: Union[GiftInfo, None, Unset] = field(factory=default_factory, kw_only=True)
    unique_gift: Union[UniqueGiftInfo, None, Unset] = field(factory=default_factory, kw_only=True)
    gift_upgrade_sent: Union[GiftInfo, None, Unset] = field(factory=default_factory, kw_only=True)
    connected_website: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    write_access_allowed: Union[WriteAccessAllowed, None, Unset] = field(factory=default_factory, kw_only=True)
    passport_data: Union[PassportData, None, Unset] = field(factory=default_factory, kw_only=True)
    proximity_alert_triggered: Union[ProximityAlertTriggered, None, Unset] = field(factory=default_factory, kw_only=True)
    boost_added: Union[ChatBoostAdded, None, Unset] = field(factory=default_factory, kw_only=True)
    chat_background_set: Union[ChatBackground, None, Unset] = field(factory=default_factory, kw_only=True)
    checklist_tasks_done: Union["ChecklistTasksDone", None, Unset] = field(factory=default_factory, kw_only=True)
    checklist_tasks_added: Union["ChecklistTasksAdded", None, Unset] = field(factory=default_factory, kw_only=True)
    direct_message_price_changed: Union[DirectMessagePriceChanged, None, Unset] = field(factory=default_factory, kw_only=True)
    forum_topic_created: Union[ForumTopicCreated, None, Unset] = field(factory=default_factory, kw_only=True)
    forum_topic_edited: Union[ForumTopicEdited, None, Unset] = field(factory=default_factory, kw_only=True)
    forum_topic_closed: Union[ForumTopicClosed, None, Unset] = field(factory=default_factory, kw_only=True)
    forum_topic_reopened: Union[ForumTopicReopened, None, Unset] = field(factory=default_factory, kw_only=True)
    general_forum_topic_hidden: Union[GeneralForumTopicHidden, None, Unset] = field(factory=default_factory, kw_only=True)
    general_forum_topic_unhidden: Union[GeneralForumTopicUnhidden, None, Unset] = field(factory=default_factory, kw_only=True)
    giveaway_created: Union[GiveawayCreated, None, Unset] = field(factory=default_factory, kw_only=True)
    giveaway: Union[Giveaway, None, Unset] = field(factory=default_factory, kw_only=True)
    giveaway_winners: Union[GiveawayWinners, None, Unset] = field(factory=default_factory, kw_only=True)
    giveaway_completed: Union["GiveawayCompleted", None, Unset] = field(factory=default_factory, kw_only=True)
    paid_message_price_changed: Union[PaidMessagePriceChanged, None, Unset] = field(factory=default_factory, kw_only=True)
    suggested_post_approved: Union["SuggestedPostApproved", None, Unset] = field(factory=default_factory, kw_only=True)
    suggested_post_approval_failed: Union["SuggestedPostApprovalFailed", None, Unset] = field(factory=default_factory, kw_only=True)
    suggested_post_declined: Union["SuggestedPostDeclined", None, Unset] = field(factory=default_factory, kw_only=True)
    suggested_post_paid: Union["SuggestedPostPaid", None, Unset] = field(factory=default_factory, kw_only=True)
    suggested_post_refunded: Union["SuggestedPostRefunded", None, Unset] = field(factory=default_factory, kw_only=True)
    video_chat_scheduled: Union[VideoChatScheduled, None, Unset] = field(factory=default_factory, kw_only=True)
    video_chat_started: Union[VideoChatStarted, None, Unset] = field(factory=default_factory, kw_only=True)
    video_chat_ended: Union[VideoChatEnded, None, Unset] = field(factory=default_factory, kw_only=True)
    video_chat_participants_invited: Union[VideoChatParticipantsInvited, None, Unset] = field(factory=default_factory, kw_only=True)
    web_app_data: Union[WebAppData, None, Unset] = field(factory=default_factory, kw_only=True)
    reply_markup: Union[InlineKeyboardMarkup, None, Unset] = field(factory=default_factory, kw_only=True)
    type: Optional[MessageType] = field(init=False)

    def __attrs_post_init__(self) -> None:
        if self.text:
            self.type = MessageType.TEXT
        elif self.animation:
            self.type = MessageType.ANIMATION
        elif self.audio:
            self.type = MessageType.AUDIO
        elif self.document:
            self.type = MessageType.DOCUMENT
        elif self.paid_media:
            self.type = MessageType.PAID_MEDIA
        elif self.photo:
            self.type = MessageType.PHOTO
        elif self.sticker:
            self.type = MessageType.STICKER
        elif self.story:
            self.type = MessageType.STORY
        elif self.video:
            self.type = MessageType.VIDEO
        elif self.video_note:
            self.type = MessageType.VIDEO_NOTE
        elif self.voice:
            self.type = MessageType.VOICE
        elif self.checklist:
            self.type = MessageType.CHECKLIST
        elif self.contact:
            self.type = MessageType.CONTACT
        elif self.dice:
            self.type = MessageType.DICE
        elif self.game:
            self.type = MessageType.GAME
        elif self.poll:
            self.type = MessageType.POLL
        elif self.venue:
            self.type = MessageType.VENUE
        elif self.location:
            self.type = MessageType.LOCATION
        elif self.new_chat_members:
            self.type = MessageType.NEW_CHAT_MEMBERS
        elif self.left_chat_member:
            self.type = MessageType.LEFT_CHAT_MEMBER
        elif self.new_chat_title:
            self.type = MessageType.NEW_CHAT_TITLE
        elif self.new_chat_photo:
            self.type = MessageType.NEW_CHAT_PHOTO
        elif self.delete_chat_photo:
            self.type = MessageType.DELETE_CHAT_PHOTO
        elif self.group_chat_created:
            self.type = MessageType.GROUP_CHAT_CREATED
        elif self.supergroup_chat_created:
            self.type = MessageType.SUPERGROUP_CHAT_CREATED
        elif self.channel_chat_created:
            self.type = MessageType.CHANNEL_CHAT_CREATED
        elif self.message_auto_delete_timer_changed:
            self.type = MessageType.MESSAGE_AUTO_DELETE_TIMER_CHANGED
        elif self.migrate_to_chat_id:
            self.type = MessageType.MIGRATE_TO_CHAT_ID
        elif self.migrate_from_chat_id:
            self.type = MessageType.MIGRATE_FROM_CHAT_ID
        elif self.pinned_message:
            self.type = MessageType.PINNED_MESSAGE
        elif self.invoice:
            self.type = MessageType.INVOICE
        elif self.successful_payment:
            self.type = MessageType.SUCCESSFUL_PAYMENT
        elif self.refunded_payment:
            self.type = MessageType.REFUNDED_PAYMENT
        elif self.users_shared:
            self.type = MessageType.USERS_SHARED
        elif self.chat_shared:
            self.type = MessageType.CHAT_SHARED
        elif self.gift:
            self.type = MessageType.GIFT
        elif self.unique_gift:
            self.type = MessageType.UNIQUE_GIFT
        elif self.connected_website:
            self.type = MessageType.CONNECTED_WEBSITE
        elif self.write_access_allowed:
            self.type = MessageType.WRITE_ACCESS_ALLOWED
        elif self.passport_data:
            self.type = MessageType.PASSPORT_DATA
        elif self.proximity_alert_triggered:
            self.type = MessageType.PROXIMITY_ALERT_TRIGGERED
        elif self.boost_added:
            self.type = MessageType.BOOST_ADDED
        elif self.chat_background_set:
            self.type = MessageType.CHAT_BACKGROUND_SET
        elif self.checklist_tasks_done:
            self.type = MessageType.CHECKLIST_TASKS_DONE
        elif self.checklist_tasks_added:
            self.type = MessageType.CHECKLIST_TASKS_ADDED
        elif self.direct_message_price_changed:
            self.type = MessageType.DIRECT_MESSAGE_PRICE_CHANGED
        elif self.forum_topic_created:
            self.type = MessageType.FORUM_TOPIC_CREATED
        elif self.forum_topic_edited:
            self.type = MessageType.FORUM_TOPIC_EDITED
        elif self.forum_topic_closed:
            self.type = MessageType.FORUM_TOPIC_CLOSED
        elif self.forum_topic_reopened:
            self.type = MessageType.FORUM_TOPIC_REOPENED
        elif self.general_forum_topic_hidden:
            self.type = MessageType.GENERAL_FORUM_TOPIC_HIDDEN
        elif self.general_forum_topic_unhidden:
            self.type = MessageType.GENERAL_FORUM_TOPIC_UNHIDDEN
        elif self.giveaway_created:
            self.type = MessageType.GIVEAWAY_CREATED
        elif self.giveaway:
            self.type = MessageType.GIVEAWAY
        elif self.giveaway_winners:
            self.type = MessageType.GIVEAWAY_WINNERS
        elif self.giveaway_completed:
            self.type = MessageType.GIVEAWAY_COMPLETED
        elif self.paid_message_price_changed:
            self.type = MessageType.PAID_MESSAGE_PRICE_CHANGED
        elif self.suggested_post_approved:
            self.type = MessageType.SUGGESTED_POST_APPROVED
        elif self.suggested_post_approval_failed:
            self.type = MessageType.SUGGESTED_POST_APPROVAL_FAILED
        elif self.suggested_post_declined:
            self.type = MessageType.SUGGESTED_POST_DECLINED
        elif self.suggested_post_paid:
            self.type = MessageType.SUGGESTED_POST_PAID
        elif self.suggested_post_refunded:
            self.type = MessageType.SUGGESTED_POST_REFUNDED
        elif self.video_chat_scheduled:
            self.type = MessageType.VIDEO_CHAT_SCHEDULED
        elif self.video_chat_started:
            self.type = MessageType.VIDEO_CHAT_STARTED
        elif self.video_chat_ended:
            self.type = MessageType.VIDEO_CHAT_ENDED
        elif self.video_chat_participants_invited:
            self.type = MessageType.VIDEO_CHAT_PARTICIPANTS_INVITED
        elif self.web_app_data:
            self.type = MessageType.WEB_APP_DATA
        else:
            self.type = None

    @property
    def chat_type(self) -> str:
        return self.chat.type

    @property
    def chat_id(self) -> int:
        return self.chat.id

    @property
    def unprefixed_chat_id(self) -> int:
        return get_unprefixed_chat_id(self.chat.id, self.chat.type)

    @property
    def user_id(self) -> Optional[int]:
        return self.from_.id if self.from_ else None

    @property
    def sender_chat_id(self) -> Optional[int]:
        return self.sender_chat.id if self.sender_chat else None

    @property
    def unprefixed_sender_chat_id(self) -> Optional[int]:
        if self.sender_chat:
            return get_unprefixed_chat_id(
                chat_id=self.sender_chat.id,
                chat_type=self.sender_chat.type
            )

    @property
    def best_photo(self) -> Optional[PhotoSize]:
        if self.photo:
            return self.photo[-1]

    @property
    def is_forwarded(self) -> bool:
        return bool(self.forward_origin)

    @property
    def is_reply(self) -> bool:
        return bool(self.reply_to_message)

    @property
    def link(self) -> Optional[str]:
        if self.chat.type != "private":
            if self.chat.username:
                return get_message_public_link(self.chat.username, self.message_id)
            else:
                return get_message_private_link(self.unprefixed_chat_id, self.message_id)

    def get_text(self, parse_mode: Optional[str] = None) -> Optional[str]:
        if self.text:
            text = self.text
        elif self.caption:
            text = self.caption
        else:
            return None

        if not text:
            return None

        if parse_mode is None:
            return text

        return get_text_formatter(parse_mode).get_formatted_text(
            text=text,
            entities=self.get_entities()
        )

    def get_entity_text(self, entity: MessageEntity) -> Optional[str]:
        text = self.get_text()

        if text:
            text = get_text_with_surrogates(text)

            return get_text_without_surrogates(text[entity.offset * 2:entity.end_offset * 2])

    def get_entities(self) -> list[MessageEntity]:
        if self.entities:
            return self.entities
        elif self.caption_entities:
            return self.caption_entities

        return []

    def get_command_args(self) -> list[str]:
        text = self.get_text()
        args = []

        if text:
            for i in text.split(" ")[1:]:
                if i:
                    args.append(i)

        return args
