# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from datetime import datetime
from typing import Literal

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.user import User


@define(repr=False)
class MessageOriginUser(Type):
    date: datetime = field()
    sender_user: User = field()
    type: Literal["user"] = field(default="user", kw_only=True)
