# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from datetime import datetime
from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.chat import Chat
from telebox.utils.unset import Unset


@define(repr=False)
class MessageOriginChat(Type):
    date: datetime = field()
    sender_chat: Chat = field()
    author_signature: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    type: Literal["chat"] = field(default="chat", kw_only=True)
