# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from datetime import datetime

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.chat import Chat
from telebox.bot.types.reaction_count import ReactionCount
from telebox.bot.utils.ids import get_unprefixed_chat_id


@define(repr=False)
class MessageReactionCountUpdated(Type):
    chat: Chat = field()
    message_id: int = field()
    date: datetime = field()
    reactions: list[ReactionCount] = field()
    
    @property
    def chat_type(self) -> str:
        return self.chat.type

    @property
    def chat_id(self) -> int:
        return self.chat.id

    @property
    def unprefixed_chat_id(self) -> int:
        return get_unprefixed_chat_id(self.chat.id, self.chat.type)
