# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from datetime import datetime
from typing import Union, Optional

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.chat import Chat
from telebox.bot.types.reaction_type import ReactionType
from telebox.bot.types.user import User
from telebox.bot.utils.ids import get_unprefixed_chat_id
from telebox.utils.unset import Unset


@define(repr=False)
class MessageReactionUpdated(Type):
    chat: Chat = field()
    message_id: int = field()
    date: datetime = field()
    old_reaction: list[ReactionType] = field()
    new_reaction: list[ReactionType] = field()
    user: Union[User, None, Unset] = field(factory=default_factory, kw_only=True)
    actor_chat: Union[Chat, None, Unset] = field(factory=default_factory, kw_only=True)
    
    @property
    def chat_type(self) -> str:
        return self.chat.type

    @property
    def chat_id(self) -> int:
        return self.chat.id

    @property
    def unprefixed_chat_id(self) -> int:
        return get_unprefixed_chat_id(self.chat.id, self.chat.type)

    @property
    def user_id(self) -> Optional[int]:
        return self.user.id if self.user else None
