# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.user import User
from telebox.utils.unset import Unset


@define(repr=False)
class MessageEntity(Type):
    type: str = field()
    offset: int = field()
    length: int = field()
    url: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    user: Union[User, None, Unset] = field(factory=default_factory, kw_only=True)
    language: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    custom_emoji_id: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    unix_time: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    date_time_format: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    
    @property
    def end_offset(self) -> int:
        return self.offset + self.length
