# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from telebox.bot.types.message_origin_channel import MessageOriginChannel
from telebox.bot.types.message_origin_chat import MessageOriginChat
from telebox.bot.types.message_origin_hidden_user import MessageOriginHiddenUser
from telebox.bot.types.message_origin_user import MessageOriginUser


MessageOrigin = Union[
    MessageOriginUser,
    MessageOriginHiddenUser,
    MessageOriginChat,
    MessageOriginChannel
]
