# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from datetime import datetime
from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.chat import Chat
from telebox.unset import Unset


@define(repr=False)
class MessageOriginChannel(Type):
    date: datetime = field()
    chat: Chat = field()
    message_id: int = field()
    author_signature: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    type: Literal["channel"] = field(default="channel", kw_only=True)
