# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.shipping_address import ShippingAddress
from telebox.utils.unset import Unset


@define(repr=False)
class OrderInfo(Type):
    name: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    phone_number: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    email: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    shipping_address: Union[ShippingAddress, None, Unset] = field(factory=default_factory, kw_only=True)
