# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from telebox.bot.types.owned_gift_regular import OwnedGiftRegular
from telebox.bot.types.owned_gift_unique import OwnedGiftUnique


OwnedGift = Union[
    OwnedGiftRegular,
    OwnedGiftUnique
]
