# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from datetime import datetime
from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.unique_gift import UniqueGift
from telebox.bot.types.user import User
from telebox.bot.utils.types import default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class OwnedGiftUnique(Type):
    gift: UniqueGift = field()
    send_date: datetime = field()
    owned_gift_id: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    sender_user: Union[User, None, Unset] = field(factory=default_factory, kw_only=True)
    is_saved: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    can_be_transferred: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    transfer_star_count: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    next_transfer_date: Union[datetime, None, Unset] = field(factory=default_factory, kw_only=True)
    type: Literal["unique"] = field(default="unique", kw_only=True)
