# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.owned_gift import OwnedGift
from telebox.bot.utils.types import default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class OwnedGifts(Type):
    total_count: int = field()
    gifts: list[OwnedGift] = field()
    next_offset: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
