# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from datetime import datetime
from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.gift import Gift
from telebox.bot.types.message_entity import MessageEntity
from telebox.bot.types.user import User
from telebox.utils.unset import Unset


@define(repr=False)
class OwnedGiftRegular(Type):
    gift: Gift = field()
    send_date: datetime = field()
    owned_gift_id: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    sender_user: Union[User, None, Unset] = field(factory=default_factory, kw_only=True)
    text: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    entities: Union[list[MessageEntity], None, Unset] = field(factory=default_factory, kw_only=True)
    is_private: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    is_saved: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    can_be_upgraded: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    was_refunded: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    convert_star_count: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    prepaid_upgrade_star_count: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    type: Literal["regular"] = field(default="regular", kw_only=True)
