# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Literal

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.video import Video


@define(repr=False)
class PaidMediaVideo(Type):
    video: Video = field()
    type: Literal["video"] = field(default="video", kw_only=True)
