# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Literal

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.photo_size import PhotoSize


@define(repr=False)
class PaidMediaPhoto(Type):
    photo: list[PhotoSize] = field()
    type: Literal["photo"] = field(default="photo", kw_only=True)
