# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.utils.types import default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class PaidMediaPreview(Type):
    width: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    height: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    duration: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    type: Literal["preview"] = field(default="preview", kw_only=True)
