# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.paid_media import PaidMedia


@define(repr=False)
class PaidMediaInfo(Type):
    star_count: int = field()
    paid_media: list[PaidMedia] = field()
