# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from telebox.bot.types.paid_media_live_photo import PaidMediaLivePhoto
from telebox.bot.types.paid_media_photo import PaidMediaPhoto
from telebox.bot.types.paid_media_preview import PaidMediaPreview
from telebox.bot.types.paid_media_video import PaidMediaVideo


PaidMedia = Union[
    PaidMediaLivePhoto,
    PaidMediaPhoto,
    PaidMediaPreview,
    PaidMediaVideo
]
