# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Literal

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.live_photo import LivePhoto


@define(repr=False)
class PaidMediaLivePhoto(Type):
    live_photo: LivePhoto = field()
    type: Literal["live_photo"] = field(default="live_photo", kw_only=True)
