# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.user import User


@define(repr=False)
class PaidMediaPurchased(Type):
    from_: User = field()
    paid_media_payload: str = field()
    
    @property
    def user_id(self) -> int:
        return self.from_.id
