# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from datetime import datetime

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class PassportFile(Type):
    file_id: str = field()
    file_unique_id: str = field()
    file_size: int = field()
    file_date: datetime = field()
