# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Literal

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class PassportElementErrorReverseSide(Type):
    type: str = field()
    file_hash: str = field()
    message: str = field()
    source: Literal["reverse_side"] = field(default="reverse_side", kw_only=True)
