# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Literal

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class PassportElementErrorTranslationFiles(Type):
    type: str = field()
    file_hashes: list[str] = field()
    message: str = field()
    source: Literal["translation_files"] = field(default="translation_files", kw_only=True)
