# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Literal

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class PassportElementErrorUnspecified(Type):
    type: str = field()
    element_hash: str = field()
    message: str = field()
    source: Literal["unspecified"] = field(default="unspecified", kw_only=True)
