# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.encrypted_credentials import EncryptedCredentials
from telebox.bot.types.encrypted_passport_element import EncryptedPassportElement


@define(repr=False)
class PassportData(Type):
    data: list[EncryptedPassportElement] = field()
    credentials: EncryptedCredentials = field()
