# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Literal

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class PassportElementErrorDataField(Type):
    type: str = field()
    field_name: str = field()
    data_hash: str = field()
    message: str = field()
    source: Literal["data"] = field(default="data", kw_only=True)
