# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Literal

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class PassportElementErrorTranslationFile(Type):
    type: str = field()
    file_hash: str = field()
    message: str = field()
    source: Literal["translation_file"] = field(default="translation_file", kw_only=True)
