# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class PhotoSize(Type):
    file_id: str = field()
    file_unique_id: str = field()
    width: int = field()
    height: int = field()
    file_size: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
