# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union, Optional

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.chat import Chat
from telebox.bot.types.user import User
from telebox.bot.utils.ids import get_unprefixed_chat_id
from telebox.bot.utils.types import default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class PollAnswer(Type):
    poll_id: str = field()
    option_ids: list[int] = field()
    voter_chat: Union[Chat, None, Unset] = field(factory=default_factory, kw_only=True)
    user: Union[User, None, Unset] = field(factory=default_factory, kw_only=True)
    
    @property
    def chat_type(self) -> Optional[str]:
        if self.voter_chat:
            return self.voter_chat.type

    @property
    def chat_id(self) -> Optional[int]:
        if self.voter_chat:
            return self.voter_chat.id

    @property
    def unprefixed_chat_id(self) -> Optional[int]:
        if self.voter_chat:
            return get_unprefixed_chat_id(self.voter_chat.id, self.voter_chat.type)

    @property
    def user_id(self) -> Optional[int]:
        if self.user:
            return self.user.id
