# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from datetime import datetime
from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.message_entity import MessageEntity
from telebox.bot.types.poll_option import PollOption
from telebox.unset import Unset


@define(repr=False)
class Poll(Type):
    id: str = field()
    question: str = field()
    options: list[PollOption] = field()
    total_voter_count: int = field()
    is_closed: bool = field()
    is_anonymous: bool = field()
    type: str = field()
    allows_multiple_answers: bool = field()
    allows_revoting: bool = field()
    question_entities: Union[list[MessageEntity], None, Unset] = field(factory=default_factory, kw_only=True)
    correct_option_ids: Union[list[int], None, Unset] = field(factory=default_factory, kw_only=True)
    explanation: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    explanation_entities: Union[list[MessageEntity], None, Unset] = field(factory=default_factory, kw_only=True)
    open_period: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    close_date: Union[datetime, None, Unset] = field(factory=default_factory, kw_only=True)
    description: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    description_entities: Union[list[MessageEntity], None, Unset] = field(factory=default_factory, kw_only=True)
