# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.maybe_inaccessible_message import MaybeInaccessibleMessage
from telebox.bot.types.message_entity import MessageEntity
from telebox.unset import Unset


@define(repr=False)
class PollOptionDeleted(Type):
    option_persistent_id: str = field()
    option_text: str = field()
    poll_message: Union[MaybeInaccessibleMessage, None, Unset] = field(factory=default_factory, kw_only=True)
    option_text_entities: Union[list[MessageEntity], None, Unset] = field(factory=default_factory, kw_only=True)
