# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.animation import Animation
from telebox.bot.types.audio import Audio
from telebox.bot.types.document import Document
from telebox.bot.types.live_photo import LivePhoto
from telebox.bot.types.location import Location
from telebox.bot.types.photo_size import PhotoSize
from telebox.bot.types.sticker import Sticker
from telebox.bot.types.venue import Venue
from telebox.bot.types.video import Video
from telebox.unset import Unset


@define(repr=False)
class PollMedia(Type):
    animation: Union[Animation, None, Unset] = field(factory=default_factory, kw_only=True)
    audio: Union[Audio, None, Unset] = field(factory=default_factory, kw_only=True)
    document: Union[Document, None, Unset] = field(factory=default_factory, kw_only=True)
    live_photo: Union[LivePhoto, None, Unset] = field(factory=default_factory, kw_only=True)
    location: Union[Location, None, Unset] = field(factory=default_factory, kw_only=True)
    photo: Union[list[PhotoSize], None, Unset] = field(factory=default_factory, kw_only=True)
    sticker: Union[Sticker, None, Unset] = field(factory=default_factory, kw_only=True)
    venue: Union[Venue, None, Unset] = field(factory=default_factory, kw_only=True)
    video: Union[Video, None, Unset] = field(factory=default_factory, kw_only=True)
