# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.order_info import OrderInfo
from telebox.bot.types.user import User
from telebox.unset import Unset


@define(repr=False)
class PreCheckoutQuery(Type):
    id: str = field()
    from_: User = field()
    currency: str = field()
    total_amount: int = field()
    invoice_payload: str = field()
    shipping_option_id: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    order_info: Union[OrderInfo, None, Unset] = field(factory=default_factory, kw_only=True)
    
    @property
    def user_id(self) -> int:
        return self.from_.id
