# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from datetime import datetime

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class PreparedInlineMessage(Type):
    id: str = field()
    expiration_date: datetime = field()
