# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Literal

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class ReactionTypeCustomEmoji(Type):
    custom_emoji_id: str = field()
    type: Literal["custom_emoji"] = field(default="custom_emoji", kw_only=True)
