# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Literal

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class ReactionTypeEmoji(Type):
    emoji: str = field()
    type: Literal["emoji"] = field(default="emoji", kw_only=True)
