# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.reaction_type import ReactionType


@define(repr=False)
class ReactionCount(Type):
    type: ReactionType = field()
    total_count: int = field()
