# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.unset import Unset


@define(repr=False)
class RefundedPayment(Type):
    currency: str = field()
    total_amount: int = field()
    invoice_payload: str = field()
    telegram_payment_charge_id: str = field()
    provider_payment_charge_id: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
