# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.keyboard_button import KeyboardButton
from telebox.bot.utils.types import default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class ReplyKeyboardMarkup(Type):
    keyboard: list[list[KeyboardButton]] = field()
    is_persistent: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    resize_keyboard: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    one_time_keyboard: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    input_field_placeholder: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    selective: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    
    @property
    def rows(self) -> int:
        return len(self.keyboard)

    def add_row(self, *buttons: KeyboardButton) -> None:
        self.keyboard.append(
            list(buttons)
        )

    def get_row_length(self, *, index: int = -1) -> int:
        return len(self.keyboard[index])

    def add_in_row(self, button: KeyboardButton, *, index: int = -1) -> None:
        self.keyboard[index].append(button)
