# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.message_entity import MessageEntity
from telebox.unset import Unset


@define(repr=False)
class ReplyParameters(Type):
    message_id: int = field()
    chat_id: Union[int, str, None, Unset] = field(factory=default_factory, kw_only=True)
    allow_sending_without_reply: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    quote: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    quote_parse_mode: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    quote_entities: Union[list[MessageEntity], None, Unset] = field(factory=default_factory, kw_only=True)
    quote_position: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    checklist_task_id: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    poll_option_id: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
