# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Literal, Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class ReplyKeyboardRemove(Type):
    remove_keyboard: Literal[True] = field()
    selective: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
