# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from telebox.bot.types.revenue_withdrawal_state_failed import RevenueWithdrawalStateFailed
from telebox.bot.types.revenue_withdrawal_state_pending import RevenueWithdrawalStatePending
from telebox.bot.types.revenue_withdrawal_state_succeeded import RevenueWithdrawalStateSucceeded


RevenueWithdrawalState = Union[
    RevenueWithdrawalStatePending,
    RevenueWithdrawalStateSucceeded,
    RevenueWithdrawalStateFailed
]
