# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from datetime import datetime
from typing import Literal

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class RevenueWithdrawalStateSucceeded(Type):
    date: datetime = field()
    url: str = field()
    type: Literal["succeeded"] = field(default="succeeded", kw_only=True)
