# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.unset import Unset


@define(repr=False)
class SentWebAppMessage(Type):
    inline_message_id: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
