# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.photo_size import PhotoSize
from telebox.unset import Unset


@define(repr=False)
class SharedUser(Type):
    user_id: int = field()
    first_name: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    last_name: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    username: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    photo: Union[list[PhotoSize], None, Unset] = field(factory=default_factory, kw_only=True)
