# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.shipping_address import ShippingAddress
from telebox.bot.types.user import User


@define(repr=False)
class ShippingQuery(Type):
    id: str = field()
    from_: User = field()
    invoice_payload: str = field()
    shipping_address: ShippingAddress = field()
    
    @property
    def user_id(self) -> int:
        return self.from_.id
