# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class ShippingAddress(Type):
    country_code: str = field()
    state: str = field()
    city: str = field()
    street_line1: str = field()
    street_line2: str = field()
    post_code: str = field()
