# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.labeled_price import LabeledPrice


@define(repr=False)
class ShippingOption(Type):
    id: str = field()
    title: str = field()
    prices: list[LabeledPrice] = field()
