# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from datetime import datetime
from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.transaction_partner import TransactionPartner
from telebox.unset import Unset


@define(repr=False)
class StarTransaction(Type):
    id: str = field()
    amount: int = field()
    date: datetime = field()
    nanostar_amount: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    source: Union[TransactionPartner, None, Unset] = field(factory=default_factory, kw_only=True)
    receiver: Union[TransactionPartner, None, Unset] = field(factory=default_factory, kw_only=True)
