# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.star_transaction import StarTransaction


@define(repr=False)
class StarTransactions(Type):
    transactions: list[StarTransaction] = field()
