# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.photo_size import PhotoSize
from telebox.bot.types.sticker import Sticker
from telebox.bot.utils.types import default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class StickerSet(Type):
    name: str = field()
    title: str = field()
    sticker_type: str = field()
    stickers: list[Sticker] = field()
    thumbnail: Union[PhotoSize, None, Unset] = field(factory=default_factory, kw_only=True)
