# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.file import File
from telebox.bot.types.mask_position import MaskPosition
from telebox.bot.types.photo_size import PhotoSize
from telebox.unset import Unset


@define(repr=False)
class Sticker(Type):
    file_id: str = field()
    file_unique_id: str = field()
    type: str = field()
    width: int = field()
    height: int = field()
    is_animated: bool = field()
    is_video: bool = field()
    thumbnail: Union[PhotoSize, None, Unset] = field(factory=default_factory, kw_only=True)
    emoji: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    set_name: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    premium_animation: Union[File, None, Unset] = field(factory=default_factory, kw_only=True)
    mask_position: Union[MaskPosition, None, Unset] = field(factory=default_factory, kw_only=True)
    custom_emoji_id: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    needs_repainting: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    file_size: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
