# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.reaction_type import ReactionType
from telebox.unset import Unset


@define(repr=False)
class StoryAreaTypeSuggestedReaction(Type):
    reaction_type: ReactionType = field()
    is_dark: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    is_flipped: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    type: Literal["suggested_reaction"] = field(default="suggested_reaction", kw_only=True)
