# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class StoryAreaPosition(Type):
    x_percentage: float = field()
    y_percentage: float = field()
    width_percentage: float = field()
    height_percentage: float = field()
    rotation_angle: float = field()
    corner_radius_percentage: float = field()
