# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Literal

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class StoryAreaTypeUniqueGift(Type):
    name: str = field()
    type: Literal["unique_gift"] = field(default="unique_gift", kw_only=True)
