# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Literal

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class StoryAreaTypeLink(Type):
    url: str = field()
    type: Literal["link"] = field(default="link", kw_only=True)
