# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.story_area_position import StoryAreaPosition
from telebox.bot.types.story_area_type import StoryAreaType


@define(repr=False)
class StoryArea(Type):
    position: StoryAreaPosition = field()
    type: StoryAreaType = field()
