# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from telebox.bot.types.story_area_type_link import StoryAreaTypeLink
from telebox.bot.types.story_area_type_location import StoryAreaTypeLocation
from telebox.bot.types.story_area_type_suggested_reaction import StoryAreaTypeSuggestedReaction
from telebox.bot.types.story_area_type_unique_gift import StoryAreaTypeUniqueGift
from telebox.bot.types.story_area_type_weather import StoryAreaTypeWeather


StoryAreaType = Union[
    StoryAreaTypeLocation,
    StoryAreaTypeSuggestedReaction,
    StoryAreaTypeLink,
    StoryAreaTypeWeather,
    StoryAreaTypeUniqueGift
]
