# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Literal

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class StoryAreaTypeWeather(Type):
    temperature: float = field()
    emoji: str = field()
    background_color: int = field()
    type: Literal["weather"] = field(default="weather", kw_only=True)
