# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from datetime import datetime
from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.order_info import OrderInfo
from telebox.unset import Unset


@define(repr=False)
class SuccessfulPayment(Type):
    currency: str = field()
    total_amount: int = field()
    invoice_payload: str = field()
    telegram_payment_charge_id: str = field()
    provider_payment_charge_id: str = field()
    subscription_expiration_date: Union[datetime, None, Unset] = field(factory=default_factory, kw_only=True)
    is_recurring: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    is_first_recurring: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    shipping_option_id: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    order_info: Union[OrderInfo, None, Unset] = field(factory=default_factory, kw_only=True)
