# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class SuggestedPostPrice(Type):
    currency: str = field()
    amount: int = field()
