# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.message import Message
from telebox.utils.unset import Unset


@define(repr=False)
class SuggestedPostDeclined(Type):
    suggested_post_message: Union[Message, None, Unset] = field(factory=default_factory, kw_only=True)
    comment: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
