# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from datetime import datetime
from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.suggested_post_price import SuggestedPostPrice
from telebox.unset import Unset


@define(repr=False)
class SuggestedPostInfo(Type):
    state: str = field()
    price: Union[SuggestedPostPrice, None, Unset] = field(factory=default_factory, kw_only=True)
    send_date: Union[datetime, None, Unset] = field(factory=default_factory, kw_only=True)
