# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.message import Message
from telebox.bot.types.star_amount import StarAmount
from telebox.utils.unset import Unset


@define(repr=False)
class SuggestedPostPaid(Type):
    currency: str = field()
    suggested_post_message: Union[Message, None, Unset] = field(factory=default_factory, kw_only=True)
    amount: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    star_amount: Union[StarAmount, None, Unset] = field(factory=default_factory, kw_only=True)
