# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.unset import Unset


@define(repr=False)
class SwitchInlineQueryChosenChat(Type):
    query: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    allow_user_chats: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    allow_bot_chats: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    allow_group_chats: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    allow_channel_chats: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
