# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.message_entity import MessageEntity
from telebox.bot.utils.types import default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class TextQuote(Type):
    text: str = field()
    position: int = field()
    entities: Union[list[MessageEntity], None, Unset] = field(factory=default_factory, kw_only=True)
    is_manual: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
