# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.chat import Chat
from telebox.bot.types.gift import Gift
from telebox.bot.utils.types import default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class TransactionPartnerChat(Type):
    chat: Chat = field()
    gift: Union[Gift, None, Unset] = field(factory=default_factory, kw_only=True)
    type: Literal["chat"] = field(default="chat", kw_only=True)
