# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Literal

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class TransactionPartnerTelegramAds(Type):
    type: Literal["telegram_ads"] = field(default="telegram_ads", kw_only=True)
