# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from telebox.bot.types.transaction_partner_affiliate_program import TransactionPartnerAffiliateProgram
from telebox.bot.types.transaction_partner_chat import TransactionPartnerChat
from telebox.bot.types.transaction_partner_fragment import TransactionPartnerFragment
from telebox.bot.types.transaction_partner_other import TransactionPartnerOther
from telebox.bot.types.transaction_partner_telegram_ads import TransactionPartnerTelegramAds
from telebox.bot.types.transaction_partner_telegram_api import TransactionPartnerTelegramApi
from telebox.bot.types.transaction_partner_user import TransactionPartnerUser


TransactionPartner = Union[
    TransactionPartnerUser,
    TransactionPartnerChat,
    TransactionPartnerAffiliateProgram,
    TransactionPartnerFragment,
    TransactionPartnerTelegramAds,
    TransactionPartnerTelegramApi,
    TransactionPartnerOther
]
