# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Literal

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class TransactionPartnerTelegramApi(Type):
    request_count: int = field()
    type: Literal["telegram_api"] = field(default="telegram_api", kw_only=True)
