# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.revenue_withdrawal_state import RevenueWithdrawalState
from telebox.bot.utils.types import default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class TransactionPartnerFragment(Type):
    withdrawal_state: Union[RevenueWithdrawalState, None, Unset] = field(factory=default_factory, kw_only=True)
    type: Literal["fragment"] = field(default="fragment", kw_only=True)
