# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.user import User
from telebox.unset import Unset


@define(repr=False)
class TransactionPartnerAffiliateProgram(Type):
    commission_per_mille: int = field()
    sponsor_user: Union[User, None, Unset] = field(factory=default_factory, kw_only=True)
    type: Literal["affiliate_program"] = field(default="affiliate_program", kw_only=True)
