# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union, Literal

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.affiliate_info import AffiliateInfo
from telebox.bot.types.gift import Gift
from telebox.bot.types.paid_media import PaidMedia
from telebox.bot.types.user import User
from telebox.utils.unset import Unset


@define(repr=False)
class TransactionPartnerUser(Type):
    transaction_type: str = field()
    user: User = field()
    affiliate: Union[AffiliateInfo, None, Unset] = field(factory=default_factory, kw_only=True)
    invoice_payload: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    subscription_period: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    paid_media: Union[list[PaidMedia], None, Unset] = field(factory=default_factory, kw_only=True)
    paid_media_payload: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    gift: Union[Gift, None, Unset] = field(factory=default_factory, kw_only=True)
    premium_subscription_duration: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    type: Literal["user"] = field(default="user", kw_only=True)
