# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Literal, Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.chat import Chat
from telebox.bot.types.unique_gift_backdrop import UniqueGiftBackdrop
from telebox.bot.types.unique_gift_colors import UniqueGiftColors
from telebox.bot.types.unique_gift_model import UniqueGiftModel
from telebox.bot.types.unique_gift_symbol import UniqueGiftSymbol
from telebox.unset import Unset


@define(repr=False)
class UniqueGift(Type):
    gift_id: str = field()
    base_name: str = field()
    name: str = field()
    number: int = field()
    model: UniqueGiftModel = field()
    symbol: UniqueGiftSymbol = field()
    backdrop: UniqueGiftBackdrop = field()
    is_premium: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    is_burned: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    is_from_blockchain: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    colors: Union[UniqueGiftColors, None, Unset] = field(factory=default_factory, kw_only=True)
    publisher_chat: Union[Chat, None, Unset] = field(factory=default_factory, kw_only=True)
