# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.unique_gift_backdrop_colors import UniqueGiftBackdropColors


@define(repr=False)
class UniqueGiftBackdrop(Type):
    name: str = field()
    colors: UniqueGiftBackdropColors = field()
    rarity_per_mille: int = field()
