# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.sticker import Sticker


@define(repr=False)
class UniqueGiftModel(Type):
    name: str = field()
    sticker: Sticker = field()
    rarity_per_mille: int = field()
