# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from datetime import datetime
from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.unique_gift import UniqueGift
from telebox.utils.unset import Unset


@define(repr=False)
class UniqueGiftInfo(Type):
    gift: UniqueGift = field()
    origin: str = field()
    last_resale_star_count: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    owned_gift_id: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    transfer_star_count: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    next_transfer_date: Union[datetime, None, Unset] = field(factory=default_factory, kw_only=True)
