# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.sticker import Sticker
from telebox.unset import Unset


@define(repr=False)
class UniqueGiftModel(Type):
    name: str = field()
    sticker: Sticker = field()
    rarity_per_mille: int = field()
    rarity: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
