# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class UniqueGiftBackdropColors(Type):
    center_color: int = field()
    edge_color: int = field()
    symbol_color: int = field()
    text_color: int = field()
