# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class UniqueGiftColors(Type):
    model_custom_emoji_id: str = field()
    symbol_custom_emoji_id: str = field()
    light_theme_main_color: int = field()
    light_theme_other_colors: list[int] = field()
    dark_theme_main_color: int = field()
    dark_theme_other_colors: list[int] = field()
