# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union, Optional, Any

from attrs import field, define

from telebox.bot.enums.update_type import UpdateType
from telebox.bot.type import Type, default_factory
from telebox.bot.types.business_connection import BusinessConnection
from telebox.bot.types.business_messages_deleted import BusinessMessagesDeleted
from telebox.bot.types.callback_query import CallbackQuery
from telebox.bot.types.chat_boost_removed import ChatBoostRemoved
from telebox.bot.types.chat_boost_updated import ChatBoostUpdated
from telebox.bot.types.chat_join_request import ChatJoinRequest
from telebox.bot.types.chat_member_updated import ChatMemberUpdated
from telebox.bot.types.chosen_inline_result import ChosenInlineResult
from telebox.bot.types.inline_query import InlineQuery
from telebox.bot.types.managed_bot_updated import ManagedBotUpdated
from telebox.bot.types.message import Message
from telebox.bot.types.message_reaction_count_updated import MessageReactionCountUpdated
from telebox.bot.types.message_reaction_updated import MessageReactionUpdated
from telebox.bot.types.paid_media_purchased import PaidMediaPurchased
from telebox.bot.types.poll import Poll
from telebox.bot.types.poll_answer import PollAnswer
from telebox.bot.types.pre_checkout_query import PreCheckoutQuery
from telebox.bot.types.shipping_query import ShippingQuery
from telebox.unset import Unset


@define(repr=False)
class Update(Type):
    update_id: int = field()
    message: Union[Message, None, Unset] = field(factory=default_factory, kw_only=True)
    edited_message: Union[Message, None, Unset] = field(factory=default_factory, kw_only=True)
    channel_post: Union[Message, None, Unset] = field(factory=default_factory, kw_only=True)
    edited_channel_post: Union[Message, None, Unset] = field(factory=default_factory, kw_only=True)
    business_connection: Union[BusinessConnection, None, Unset] = field(factory=default_factory, kw_only=True)
    business_message: Union[Message, None, Unset] = field(factory=default_factory, kw_only=True)
    edited_business_message: Union[Message, None, Unset] = field(factory=default_factory, kw_only=True)
    deleted_business_messages: Union[BusinessMessagesDeleted, None, Unset] = field(factory=default_factory, kw_only=True)
    guest_message: Union[Message, None, Unset] = field(factory=default_factory, kw_only=True)
    message_reaction: Union[MessageReactionUpdated, None, Unset] = field(factory=default_factory, kw_only=True)
    message_reaction_count: Union[MessageReactionCountUpdated, None, Unset] = field(factory=default_factory, kw_only=True)
    inline_query: Union[InlineQuery, None, Unset] = field(factory=default_factory, kw_only=True)
    chosen_inline_result: Union[ChosenInlineResult, None, Unset] = field(factory=default_factory, kw_only=True)
    callback_query: Union[CallbackQuery, None, Unset] = field(factory=default_factory, kw_only=True)
    shipping_query: Union[ShippingQuery, None, Unset] = field(factory=default_factory, kw_only=True)
    pre_checkout_query: Union[PreCheckoutQuery, None, Unset] = field(factory=default_factory, kw_only=True)
    purchased_paid_media: Union[PaidMediaPurchased, None, Unset] = field(factory=default_factory, kw_only=True)
    poll: Union[Poll, None, Unset] = field(factory=default_factory, kw_only=True)
    poll_answer: Union[PollAnswer, None, Unset] = field(factory=default_factory, kw_only=True)
    my_chat_member: Union[ChatMemberUpdated, None, Unset] = field(factory=default_factory, kw_only=True)
    chat_member: Union[ChatMemberUpdated, None, Unset] = field(factory=default_factory, kw_only=True)
    chat_join_request: Union[ChatJoinRequest, None, Unset] = field(factory=default_factory, kw_only=True)
    chat_boost: Union[ChatBoostUpdated, None, Unset] = field(factory=default_factory, kw_only=True)
    removed_chat_boost: Union[ChatBoostRemoved, None, Unset] = field(factory=default_factory, kw_only=True)
    managed_bot: Union[ManagedBotUpdated, None, Unset] = field(factory=default_factory, kw_only=True)
    type: Optional[UpdateType] = field(init=False)
    content: Any = field(init=False)

    def __attrs_post_init__(self) -> None:
        if self.message:
            self.type = UpdateType.MESSAGE
            self.content = self.message
        elif self.edited_message:
            self.type = UpdateType.EDITED_MESSAGE
            self.content = self.edited_message
        elif self.channel_post:
            self.type = UpdateType.CHANNEL_POST
            self.content = self.channel_post
        elif self.edited_channel_post:
            self.type = UpdateType.EDITED_CHANNEL_POST
            self.content = self.edited_channel_post
        elif self.business_connection:
            self.type = UpdateType.BUSINESS_CONNECTION
            self.content = self.business_connection
        elif self.business_message:
            self.type = UpdateType.BUSINESS_MESSAGE
            self.content = self.business_message
        elif self.edited_business_message:
            self.type = UpdateType.EDITED_BUSINESS_MESSAGE
            self.content = self.edited_business_message
        elif self.deleted_business_messages:
            self.type = UpdateType.DELETED_BUSINESS_MESSAGES
            self.content = self.deleted_business_messages
        elif self.guest_message:
            self.type = UpdateType.GUEST_MESSAGE
            self.content = self.guest_message
        elif self.message_reaction:
            self.type = UpdateType.MESSAGE_REACTION
            self.content = self.message_reaction
        elif self.message_reaction_count:
            self.type = UpdateType.MESSAGE_REACTION_COUNT
            self.content = self.message_reaction_count
        elif self.inline_query:
            self.type = UpdateType.INLINE_QUERY
            self.content = self.inline_query
        elif self.chosen_inline_result:
            self.type = UpdateType.CHOSEN_INLINE_RESULT
            self.content = self.chosen_inline_result
        elif self.callback_query:
            self.type = UpdateType.CALLBACK_QUERY
            self.content = self.callback_query
        elif self.shipping_query:
            self.type = UpdateType.SHIPPING_QUERY
            self.content = self.shipping_query
        elif self.pre_checkout_query:
            self.type = UpdateType.PRE_CHECKOUT_QUERY
            self.content = self.pre_checkout_query
        elif self.purchased_paid_media:
            self.type = UpdateType.PURCHASED_PAID_MEDIA
            self.content = self.purchased_paid_media
        elif self.poll:
            self.type = UpdateType.POLL
            self.content = self.poll
        elif self.poll_answer:
            self.type = UpdateType.POLL_ANSWER
            self.content = self.poll_answer
        elif self.my_chat_member:
            self.type = UpdateType.MY_CHAT_MEMBER
            self.content = self.my_chat_member
        elif self.chat_member:
            self.type = UpdateType.CHAT_MEMBER
            self.content = self.chat_member
        elif self.chat_join_request:
            self.type = UpdateType.CHAT_JOIN_REQUEST
            self.content = self.chat_join_request
        elif self.chat_boost:
            self.type = UpdateType.CHAT_BOOST
            self.content = self.chat_boost
        elif self.removed_chat_boost:
            self.type = UpdateType.REMOVED_CHAT_BOOST
            self.content = self.removed_chat_boost
        elif self.managed_bot:
            self.type = UpdateType.MANAGED_BOT
            self.content = self.managed_bot
        else:
            self.type = None
            self.content = None
