# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.shared_user import SharedUser


@define(repr=False)
class UsersShared(Type):
    request_id: int = field()
    users: list[SharedUser] = field()
