# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.unset import Unset


@define(repr=False)
class UserRating(Type):
    level: int = field()
    rating: int = field()
    current_level_rating: int = field()
    next_level_rating: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
