# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union, Literal, Optional

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.utils.links import get_username_link, get_user_link
from telebox.bot.utils.users import get_full_name
from telebox.unset import Unset


@define(repr=False)
class User(Type):
    id: int = field()
    is_bot: bool = field()
    first_name: str = field()
    last_name: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    username: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    language_code: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    is_premium: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    added_to_attachment_menu: Union[Literal[True], None, Unset] = field(factory=default_factory, kw_only=True)
    can_join_groups: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    can_read_all_group_messages: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    supports_inline_queries: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    can_connect_to_business: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    has_main_web_app: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    has_topics_enabled: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    allows_users_to_create_topics: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    
    @property
    def full_name(self) -> str:
        return get_full_name(self.first_name, self.last_name)

    @property
    def link(self) -> Optional[str]:
        if self.username:
            return get_username_link(self.username)

    @property
    def mention_link(self) -> str:
        return get_user_link(self.id)
