# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.photo_size import PhotoSize


@define(repr=False)
class UserProfilePhotos(Type):
    total_count: int = field()
    photos: list[list[PhotoSize]] = field()
