# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.types.audio import Audio


@define(repr=False)
class UserProfileAudios(Type):
    total_count: int = field()
    audios: list[Audio] = field()
