# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.location import Location
from telebox.utils.unset import Unset


@define(repr=False)
class Venue(Type):
    location: Location = field()
    title: str = field()
    address: str = field()
    foursquare_id: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    foursquare_type: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    google_place_id: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    google_place_type: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
