# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from datetime import datetime

from attrs import define, field

from telebox.bot.type import Type


@define(repr=False)
class VideoChatScheduled(Type):
    start_date: datetime = field()
