# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.bot.types.photo_size import PhotoSize
from telebox.unset import Unset


@define(repr=False)
class VideoNote(Type):
    file_id: str = field()
    file_unique_id: str = field()
    length: int = field()
    duration: int = field()
    thumbnail: Union[PhotoSize, None, Unset] = field(factory=default_factory, kw_only=True)
    file_size: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
