# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type, default_factory
from telebox.unset import Unset


@define(repr=False)
class Voice(Type):
    file_id: str = field()
    file_unique_id: str = field()
    duration: int = field()
    mime_type: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    file_size: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
