# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from datetime import datetime
from typing import Union

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.utils.types import default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class WebhookInfo(Type):
    url: str = field()
    has_custom_certificate: bool = field()
    pending_update_count: int = field()
    ip_address: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    last_error_date: Union[datetime, None, Unset] = field(factory=default_factory, kw_only=True)
    last_error_message: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    last_synchronization_error_date: Union[datetime, None, Unset] = field(factory=default_factory, kw_only=True)
    max_connections: Union[int, None, Unset] = field(factory=default_factory, kw_only=True)
    allowed_updates: Union[list[str], None, Unset] = field(factory=default_factory, kw_only=True)
