# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union

from attrs import define, field

from telebox.bot.type import Type
from telebox.bot.utils.types import default_factory
from telebox.utils.unset import Unset


@define(repr=False)
class WriteAccessAllowed(Type):
    from_request: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
    web_app_name: Union[str, None, Unset] = field(factory=default_factory, kw_only=True)
    from_attachment_menu: Union[bool, None, Unset] = field(factory=default_factory, kw_only=True)
