# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

import logging
from typing import Optional, Union, NoReturn, Callable, Iterable
from collections import deque
from queue import Queue, SimpleQueue
import threading
from threading import Thread, RLock, Condition, Event
import signal
from signal import Signals, SIGINT, SIGTERM
import time

from telebox.bot.bot import Bot
from telebox.bot.types.update import Update
from telebox.bot.types.message import Message
from telebox.dispatcher.types.media_group import MediaGroup
from telebox.dispatcher.enums.event_type import EventType
from telebox.dispatcher.enums.processing_status import ProcessingStatus
from telebox.dispatcher.filter import AbstractBaseFilter
from telebox.dispatcher.filters.empty import EmptyFilter
from telebox.dispatcher.middleware import Middleware
from telebox.dispatcher.router import Router
from telebox.dispatcher.listener import AbstractListener
from telebox.dispatcher.types.event_info import EventInfo
from telebox.dispatcher.types.handler_info import HandlerInfo
from telebox.dispatcher.types.error_handler_info import ErrorHandlerInfo
from telebox.dispatcher.abort import Abort
from telebox.dispatcher.type_hints import Handler, ErrorHandler
from telebox.context_values import event_context, handler_context, error_handler_context
from telebox.dispatcher.context import EventContext
from telebox.dispatcher.drafts.storage import AbstractDraftStorage
from telebox.state_machine.machine import StateMachine
from telebox.deps import DepsBase


logger = logging.getLogger(__name__)

_empty_filter = EmptyFilter()
_WORKER_WAITING_SECS = 60
_EVENT_PROCESSING_LOG_TEMPLATES = {
    ProcessingStatus.PROCESSING: "Event processing completed: %r.",
    ProcessingStatus.ABORTED: "Event processing aborted: %r.",
    ProcessingStatus.HANDLER_NOT_FOUND: "No handler for event: %r.",
    ProcessingStatus.ADDED_TO_CHAT_QUEUE: "Event added to chat queue: %r."
}


class MediaGroupContainer:
    def __init__(self, event: Message, event_type: EventType):
        self.events = [event]
        self.event_type = event_type
        self.time = time.monotonic()

    def add_event(self, event: Message) -> None:
        self.events.append(event)
        self.time = time.monotonic()


class Dispatcher:
    def __init__(
        self,
        listener: AbstractListener,
        deps: DepsBase,
        *,
        min_workers: int = 10,
        max_workers: int = 100,
        bot: Optional[Bot] = None,
        state_machine: Optional[StateMachine] = None,
        draft_storage: Optional[AbstractDraftStorage] = None,
        media_group_timeout: Union[int, float] = 3
    ):
        self._listener = listener
        self._deps = deps
        self._min_workers = min_workers
        self._max_workers = max_workers
        self._bot = bot
        self._state_machine = state_machine
        self._draft_storage = draft_storage
        self._media_group_timeout = media_group_timeout
        self._updates: Queue[Update] = Queue()
        self._events: deque[EventInfo] = deque()
        self._processing_chat_ids: set[int] = set()
        self._chat_queues: dict[int, SimpleQueue[EventInfo]] = {}
        self._unprocessed_events = 0
        self._event_lock = RLock()
        self._new_event_condition = Condition(self._event_lock)
        self._all_events_processed_condition = Condition(self._event_lock)
        self._workers: dict[str, Thread] = {}
        self._update_worker: Optional[Thread] = None
        self._media_group_worker: Optional[Thread] = None
        self._worker_lock = RLock()
        self._worker_count = 0
        self._handlers: dict[EventType, list[HandlerInfo]] = {i: [] for i in EventType}
        self._error_handlers: list[ErrorHandlerInfo] = []
        self._middlewares: list[Middleware] = []
        self._media_group_containers: dict[str, MediaGroupContainer] = {}
        self._media_group_lock = RLock()

    def add_business_connection_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._add_handler(
            handler=handler,
            event_type=EventType.BUSINESS_CONNECTION,
            filter_=filter_
        )

    def add_business_message_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._add_handler(
            handler=handler,
            event_type=EventType.BUSINESS_MESSAGE,
            filter_=filter_
        )

    def add_callback_query_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None,
        *,
        with_chat_queue: bool = True
    ) -> None:
        self._add_handler(
            handler=handler,
            event_type=EventType.CALLBACK_QUERY,
            filter_=filter_,
            with_chat_queue=with_chat_queue
        )

    def add_channel_media_group_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None,
        *,
        with_chat_queue: bool = True
    ) -> None:
        self._add_handler(
            handler=handler,
            event_type=EventType.CHANNEL_MEDIA_GROUP,
            filter_=filter_,
            with_chat_queue=with_chat_queue
        )

    def add_channel_post_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None,
        *,
        with_chat_queue: bool = True
    ) -> None:
        self._add_handler(
            handler=handler,
            event_type=EventType.CHANNEL_POST,
            filter_=filter_,
            with_chat_queue=with_chat_queue
        )

    def add_chat_boost_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._add_handler(
            handler=handler,
            event_type=EventType.CHAT_BOOST,
            filter_=filter_
        )

    def add_chat_join_request_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._add_handler(
            handler=handler,
            event_type=EventType.CHAT_JOIN_REQUEST,
            filter_=filter_
        )

    def add_chat_member_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._add_handler(
            handler=handler,
            event_type=EventType.CHAT_MEMBER,
            filter_=filter_
        )

    def add_chosen_inline_result_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._add_handler(
            handler=handler,
            event_type=EventType.CHOSEN_INLINE_RESULT,
            filter_=filter_
        )

    def add_deleted_business_messages_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._add_handler(
            handler=handler,
            event_type=EventType.DELETED_BUSINESS_MESSAGES,
            filter_=filter_
        )

    def add_edited_business_message_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._add_handler(
            handler=handler,
            event_type=EventType.EDITED_BUSINESS_MESSAGE,
            filter_=filter_
        )

    def add_edited_channel_post_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None,
        *,
        with_chat_queue: bool = True
    ) -> None:
        self._add_handler(
            handler=handler,
            event_type=EventType.EDITED_CHANNEL_POST,
            filter_=filter_,
            with_chat_queue=with_chat_queue
        )

    def add_edited_message_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None,
        *,
        with_chat_queue: bool = True
    ) -> None:
        self._add_handler(
            handler=handler,
            event_type=EventType.EDITED_MESSAGE,
            filter_=filter_,
            with_chat_queue=with_chat_queue
        )

    def add_inline_query_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._add_handler(
            handler=handler,
            event_type=EventType.INLINE_QUERY,
            filter_=filter_
        )

    def add_media_group_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None,
        *,
        with_chat_queue: bool = True
    ) -> None:
        self._add_handler(
            handler=handler,
            event_type=EventType.MEDIA_GROUP,
            filter_=filter_,
            with_chat_queue=with_chat_queue
        )

    def add_message_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None,
        *,
        with_chat_queue: bool = True
    ) -> None:
        self._add_handler(
            handler=handler,
            event_type=EventType.MESSAGE,
            filter_=filter_,
            with_chat_queue=with_chat_queue
        )

    def add_message_reaction_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._add_handler(
            handler=handler,
            event_type=EventType.MESSAGE_REACTION,
            filter_=filter_
        )

    def add_message_reaction_count_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._add_handler(
            handler=handler,
            event_type=EventType.MESSAGE_REACTION_COUNT,
            filter_=filter_
        )

    def add_my_chat_member_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._add_handler(
            handler=handler,
            event_type=EventType.MY_CHAT_MEMBER,
            filter_=filter_
        )

    def add_poll_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._add_handler(
            handler=handler,
            event_type=EventType.POLL,
            filter_=filter_
        )

    def add_poll_answer_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._add_handler(
            handler=handler,
            event_type=EventType.POLL_ANSWER,
            filter_=filter_
        )

    def add_pre_checkout_query_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._add_handler(
            handler=handler,
            event_type=EventType.PRE_CHECKOUT_QUERY,
            filter_=filter_
        )

    def add_purchased_paid_media_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._add_handler(
            handler=handler,
            event_type=EventType.PURCHASED_PAID_MEDIA,
            filter_=filter_
        )

    def add_removed_chat_boost_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._add_handler(
            handler=handler,
            event_type=EventType.REMOVED_CHAT_BOOST,
            filter_=filter_
        )

    def add_shipping_query_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._add_handler(
            handler=handler,
            event_type=EventType.SHIPPING_QUERY,
            filter_=filter_
        )

    def add_error_handler(
        self,
        handler: ErrorHandler,
        error_type: type[Exception] = Exception
    ) -> None:
        self._error_handlers.append(
            ErrorHandlerInfo(
                handler=handler,
                error_type=error_type
            )
        )

    def get_router(self, filter_: AbstractBaseFilter) -> Router:
        return Router(dispatcher=self, filter_=filter_)

    def add_middleware(self, middleware: Middleware) -> None:
        for i in self._middlewares:
            if i is middleware:
                raise ValueError(f"Middleware {middleware!r} is already added!")

        self._middlewares.append(middleware)

    def run(self) -> None:
        self._create_workers()
        self._listener.run(self._updates)

        logger.info("Finishing update processing...")

        self._updates.join()
        self._wait_events()

        logger.info("Update processing completed.")

    def stop(self) -> None:
        self._listener.stop()

    def set_signal_handler(
        self,
        callback: Optional[Callable] = None,
        *,
        signals: Iterable[int] = (SIGINT, SIGTERM)
    ) -> Event:
        stop_event = Event()

        def stop(signal_number: int, _) -> None:
            signal_name = Signals(signal_number).name
            logger.info("Signal handler called with signal %r (%r).", signal_name, signal_number)

            if callback is not None:
                try:
                    callback()
                except Exception:  # noqa
                    logger.exception("An error occurred while calling signal callback!")

            stop_event.set()
            self.stop()

        for i in signals:
            signal.signal(i, stop)

        return stop_event

    def _create_workers(self) -> None:
        self._update_worker = Thread(
            target=self._run_update_processing,
            name="UpdateWorker",
            daemon=True
        )
        self._media_group_worker = Thread(
            target=self._run_media_group_collecting,
            name="MediaGroupWorker",
            daemon=True
        )

        self._update_worker.start()
        self._media_group_worker.start()

        with self._worker_lock:
            for _ in range(self._min_workers):
                self._create_worker()

    def _add_handler(
        self,
        handler: Handler,
        event_type: EventType,
        filter_: Optional[AbstractBaseFilter] = None,
        with_chat_queue: bool = False
    ) -> None:
        self._handlers[event_type].append(
            HandlerInfo(
                handler=handler,
                filter=filter_ or _empty_filter,
                with_chat_queue=with_chat_queue
            )
        )

    def _get_handler(self, event_info: EventInfo) -> Optional[HandlerInfo]:
        filter_results: dict[AbstractBaseFilter, bool] = {}

        for i in self._handlers[event_info.event_type]:
            if not i.filter in filter_results:
                filter_results[i.filter] = i.filter.get_result(event_info.event)

            if filter_results[i.filter]:
                return i

    def _get_error_handler(self, error: Exception) -> Optional[ErrorHandlerInfo]:
        for i in self._error_handlers:
            if isinstance(error, i.error_type):
                return i

    def _create_worker(self) -> None:
        self._worker_count += 1
        worker = Thread(
            target=self._run_event_processing,
            name=f"EventWorker-{self._worker_count}",
            daemon=True
        )
        self._workers[worker.name] = worker
        logger.debug(
            "Worker %r started (workers: %r).",
            worker.name,
            len(self._workers)
        )
        worker.start()

    def _run_media_group_collecting(self) -> NoReturn:
        while True:
            with self._media_group_lock:
                for media_group_id in tuple(self._media_group_containers):
                    secs = time.monotonic() - self._media_group_containers[media_group_id].time

                    if secs > self._media_group_timeout:
                        container = self._media_group_containers.pop(media_group_id)
                        event = MediaGroup(container.events)

                        if container.event_type is EventType.MESSAGE:
                            event_type = EventType.MEDIA_GROUP
                        elif container.event_type is EventType.CHANNEL_POST:
                            event_type = EventType.CHANNEL_MEDIA_GROUP
                        else:
                            raise RuntimeError(
                                f"Unknown message type {container.event_type!r}!"
                            )

                        self._add_event_to_queue(
                            EventInfo(
                                event=event,
                                event_type=event_type
                            )
                        )

            time.sleep(0.1)

    def _add_event_to_queue(self, event_info: EventInfo) -> None:
        with self._new_event_condition:
            self._events.append(event_info)
            self._unprocessed_events += 1
            logger.debug(
                "Event added to queue: %r (events: %r).",
                event_info.event,
                len(self._events)
            )
            self._new_event_condition.notify()

            with self._worker_lock:
                if (
                    (self._unprocessed_events > len(self._workers))
                    and (len(self._workers) < self._max_workers)
                ):
                    self._create_worker()

    def _wait_events(self) -> None:
        with self._all_events_processed_condition:
            while self._unprocessed_events:
                self._all_events_processed_condition.wait()

    def _set_event_completion(self) -> None:
        with self._all_events_processed_condition:
            self._unprocessed_events -= 1

            if not self._unprocessed_events:
                self._all_events_processed_condition.notify_all()

    def _set_chat_event_completion(self, chat_id: int) -> None:
        with self._new_event_condition:
            chat_events = self._chat_queues.get(chat_id)

            if chat_events is None:
                self._processing_chat_ids.remove(chat_id)

                return

            next_event = chat_events.get_nowait()
            next_event.from_chat_queue = True

            if chat_events.empty():
                del self._chat_queues[chat_id]

            self._events.append(next_event)
            self._new_event_condition.notify()

    def _process_event(self, event_info: EventInfo) -> None:
        logger.debug("Event processing started: %r.", event_info.event)
        context = EventContext(
            event=event_info.event,
            event_type=event_info.event_type,
            deps=self._deps,
            chat_id=event_info.chat_id,
            user_id=event_info.user_id,
            bot=self._bot,
            state_machine=self._state_machine,
            draft_storage=self._draft_storage
        )

        try:
            event_context.set(event_info.event)

            if not event_info.middleware_pre_processed:
                for i in self._middlewares:
                    i.pre_process_event(context)

                event_info.middleware_pre_processed = True

            handler_info = self._get_handler(event_info)

            if handler_info is None:
                event_info.processing_status = ProcessingStatus.HANDLER_NOT_FOUND

                return

            if handler_info.with_chat_queue and (event_info.chat_id is not None):
                event_info.with_chat_queue = True

                if not event_info.from_chat_queue:
                    with self._event_lock:
                        if event_info.chat_id in self._processing_chat_ids:
                            chat_events = self._chat_queues.get(event_info.chat_id)

                            if chat_events is None:
                                chat_events = self._chat_queues[event_info.chat_id] = SimpleQueue()

                            chat_events.put_nowait(event_info)
                            event_info.processing_status = ProcessingStatus.ADDED_TO_CHAT_QUEUE

                            return
                        else:
                            self._processing_chat_ids.add(event_info.chat_id)

            handler_context.set(handler_info.handler)
            context.handler = handler_info.handler

            for i in self._middlewares:
                i.process_event(context)

            handler_info.handler(context)

            for i in self._middlewares:
                i.post_process_event(context)
        except Abort:
            event_info.processing_status = ProcessingStatus.ABORTED
        except Exception as error:
            event_info.processing_status = ProcessingStatus.ERROR_OCCURRED
            context.error = error

            try:
                error_handler_info = self._get_error_handler(error)

                if error_handler_info is None:
                    raise error

                error_handler_context.set(error_handler_info.handler)
                context.error_handler = error_handler_info.handler

                for i in self._middlewares:
                    i.process_error(context)

                error_handler_info.handler(context)
            except Exception:
                logger.exception("An error occurred while processing the event %r!", event_info.event)
        finally:
            if event_info.processing_status is not ProcessingStatus.ERROR_OCCURRED:
                logger.debug(
                    _EVENT_PROCESSING_LOG_TEMPLATES[event_info.processing_status],
                    event_info.event
                )

            if event_info.processing_status is ProcessingStatus.ADDED_TO_CHAT_QUEUE:
                event_info.processing_status = ProcessingStatus.PROCESSING

                return

            if event_info.with_chat_queue:
                self._set_chat_event_completion(chat_id=event_info.chat_id)

            self._set_event_completion()

    def _run_update_processing(self) -> None:
        while True:
            update = self._updates.get()

            try:
                event = update.content

                if event is None:
                    logger.debug(
                        "Update dropped because it has an unknown type: %r.",
                        update
                    )
                    continue

                event_type = EventType(update.type.value)

                if (
                    (event_type in (EventType.MESSAGE, EventType.CHANNEL_POST))
                    and (event.media_group_id is not None)
                ):
                    event: Message

                    with self._media_group_lock:
                        if event.media_group_id not in self._media_group_containers:
                            self._media_group_containers[event.media_group_id] = MediaGroupContainer(
                                event=event,
                                event_type=event_type
                            )
                        else:
                            self._media_group_containers[event.media_group_id].add_event(event)

                    continue

                self._add_event_to_queue(
                    EventInfo(
                        event=event,
                        event_type=event_type
                    )
                )
            finally:
                self._updates.task_done()

    def _run_event_processing(self) -> None:
        worker_name = threading.current_thread().name
        last_processing_time = time.monotonic()

        while True:
            with self._new_event_condition:
                while not self._events:
                    remaining_secs = (
                        _WORKER_WAITING_SECS
                        - (time.monotonic() - last_processing_time)
                    )

                    if remaining_secs <= 0:
                        with self._worker_lock:
                            if len(self._workers) > self._min_workers:
                                del self._workers[worker_name]
                                logger.debug(
                                    "Worker %r stopped (workers: %r).",
                                    worker_name,
                                    len(self._workers)
                                )

                                return
                            else:
                                remaining_secs = _WORKER_WAITING_SECS

                    self._new_event_condition.wait(timeout=remaining_secs)

                event = self._events.popleft()

            self._process_event(event)
            last_processing_time = time.monotonic()
