# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Optional, Union, TYPE_CHECKING

from telebox.dispatcher.filter import AbstractBaseFilter
from telebox.dispatcher.type_hints import Handler
if TYPE_CHECKING:
    from telebox.dispatcher.dispatcher import Dispatcher


class Router:
    def __init__(
        self,
        dispatcher: "Dispatcher",
        filter_: AbstractBaseFilter
    ):
        self._dispatcher = dispatcher
        self.filter = filter_

    def __add__(self, other: Union[AbstractBaseFilter, "Router"]) -> "Router":
        if isinstance(other, AbstractBaseFilter):
            return Router(self._dispatcher, self._get_filter(other))
        elif isinstance(other, Router):
            return Router(self._dispatcher, self._get_filter(other.filter))

        return NotImplemented

    def __iadd__(self, other: Union[AbstractBaseFilter, "Router"]) -> "Router":
        return self.__add__(other)

    def add_business_connection_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._dispatcher.add_business_connection_handler(
            handler=handler,
            filter_=self._get_filter(filter_)
        )

    def add_business_message_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._dispatcher.add_business_message_handler(
            handler=handler,
            filter_=self._get_filter(filter_)
        )

    def add_callback_query_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None,
        *,
        use_chat_queue: bool = True
    ) -> None:
        self._dispatcher.add_callback_query_handler(
            handler=handler,
            filter_=self._get_filter(filter_),
            use_chat_queue=use_chat_queue
        )

    def add_channel_media_group_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None,
        *,
        use_chat_queue: bool = True
    ) -> None:
        self._dispatcher.add_channel_media_group_handler(
            handler=handler,
            filter_=self._get_filter(filter_),
            use_chat_queue=use_chat_queue
        )

    def add_channel_post_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None,
        *,
        use_chat_queue: bool = True
    ) -> None:
        self._dispatcher.add_channel_post_handler(
            handler=handler,
            filter_=self._get_filter(filter_),
            use_chat_queue=use_chat_queue
        )

    def add_chat_boost_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._dispatcher.add_chat_boost_handler(
            handler=handler,
            filter_=self._get_filter(filter_)
        )

    def add_chat_join_request_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._dispatcher.add_chat_join_request_handler(
            handler=handler,
            filter_=self._get_filter(filter_)
        )

    def add_chat_member_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._dispatcher.add_chat_member_handler(
            handler=handler,
            filter_=self._get_filter(filter_)
        )

    def add_chosen_inline_result_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._dispatcher.add_chosen_inline_result_handler(
            handler=handler,
            filter_=self._get_filter(filter_)
        )

    def add_deleted_business_messages_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._dispatcher.add_deleted_business_messages_handler(
            handler=handler,
            filter_=self._get_filter(filter_)
        )

    def add_edited_business_message_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._dispatcher.add_edited_business_message_handler(
            handler=handler,
            filter_=self._get_filter(filter_)
        )

    def add_edited_channel_post_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None,
        *,
        use_chat_queue: bool = True
    ) -> None:
        self._dispatcher.add_edited_channel_post_handler(
            handler=handler,
            filter_=self._get_filter(filter_),
            use_chat_queue=use_chat_queue
        )

    def add_edited_message_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None,
        *,
        use_chat_queue: bool = True
    ) -> None:
        self._dispatcher.add_edited_message_handler(
            handler=handler,
            filter_=self._get_filter(filter_),
            use_chat_queue=use_chat_queue
        )

    def add_guest_message_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._dispatcher.add_guest_message_handler(
            handler=handler,
            filter_=self._get_filter(filter_)
        )

    def add_inline_query_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._dispatcher.add_inline_query_handler(
            handler=handler,
            filter_=self._get_filter(filter_)
        )

    def add_managed_bot_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._dispatcher.add_managed_bot_handler(
            handler=handler,
            filter_=self._get_filter(filter_)
        )

    def add_media_group_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None,
        *,
        use_chat_queue: bool = True
    ) -> None:
        self._dispatcher.add_media_group_handler(
            handler=handler,
            filter_=self._get_filter(filter_),
            use_chat_queue=use_chat_queue
        )

    def add_message_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None,
        *,
        use_chat_queue: bool = True
    ) -> None:
        self._dispatcher.add_message_handler(
            handler=handler,
            filter_=self._get_filter(filter_),
            use_chat_queue=use_chat_queue
        )

    def add_message_reaction_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._dispatcher.add_message_reaction_handler(
            handler=handler,
            filter_=self._get_filter(filter_)
        )

    def add_message_reaction_count_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._dispatcher.add_message_reaction_count_handler(
            handler=handler,
            filter_=self._get_filter(filter_)
        )

    def add_my_chat_member_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._dispatcher.add_my_chat_member_handler(
            handler=handler,
            filter_=self._get_filter(filter_)
        )

    def add_poll_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._dispatcher.add_poll_handler(
            handler=handler,
            filter_=self._get_filter(filter_)
        )

    def add_poll_answer_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._dispatcher.add_poll_answer_handler(
            handler=handler,
            filter_=self._get_filter(filter_)
        )

    def add_pre_checkout_query_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._dispatcher.add_pre_checkout_query_handler(
            handler=handler,
            filter_=self._get_filter(filter_)
        )

    def add_purchased_paid_media_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._dispatcher.add_purchased_paid_media_handler(
            handler=handler,
            filter_=self._get_filter(filter_)
        )

    def add_removed_chat_boost_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._dispatcher.add_removed_chat_boost_handler(
            handler=handler,
            filter_=self._get_filter(filter_)
        )

    def add_shipping_query_handler(
        self,
        handler: Handler,
        filter_: Optional[AbstractBaseFilter] = None
    ) -> None:
        self._dispatcher.add_shipping_query_handler(
            handler=handler,
            filter_=self._get_filter(filter_)
        )

    def _get_filter(
        self,
        filter_: Optional[AbstractBaseFilter]
    ) -> Optional[AbstractBaseFilter]:
        if filter_ is None:
            return self.filter

        return self.filter & filter_
