# This file was automatically generated by `apicodegen`.
# DO NOT EDIT THIS FILE MANUALLY!

from typing import Union, Callable

from telebox.bot.types.business_connection import BusinessConnection
from telebox.bot.types.business_messages_deleted import BusinessMessagesDeleted
from telebox.bot.types.callback_query import CallbackQuery
from telebox.bot.types.chat_boost_removed import ChatBoostRemoved
from telebox.bot.types.chat_boost_updated import ChatBoostUpdated
from telebox.bot.types.chat_join_request import ChatJoinRequest
from telebox.bot.types.chat_member_updated import ChatMemberUpdated
from telebox.bot.types.chosen_inline_result import ChosenInlineResult
from telebox.bot.types.inline_query import InlineQuery
from telebox.bot.types.message import Message
from telebox.bot.types.message_reaction_count_updated import MessageReactionCountUpdated
from telebox.bot.types.message_reaction_updated import MessageReactionUpdated
from telebox.bot.types.paid_media_purchased import PaidMediaPurchased
from telebox.bot.types.poll import Poll
from telebox.bot.types.poll_answer import PollAnswer
from telebox.bot.types.pre_checkout_query import PreCheckoutQuery
from telebox.bot.types.shipping_query import ShippingQuery
from telebox.dispatcher.types.media_group import MediaGroup
from telebox.utils.data import Data
from telebox.utils.deps import Deps


Event = Union[
    BusinessConnection,
    BusinessMessagesDeleted,
    CallbackQuery,
    ChatBoostRemoved,
    ChatBoostUpdated,
    ChatJoinRequest,
    ChatMemberUpdated,
    ChosenInlineResult,
    InlineQuery,
    MediaGroup,
    Message,
    MessageReactionCountUpdated,
    MessageReactionUpdated,
    PaidMediaPurchased,
    Poll,
    PollAnswer,
    PreCheckoutQuery,
    ShippingQuery
]
Handler = Callable[[Event, Deps, Data], None]
ErrorHandler = Callable[[Exception, Event, Deps], None]
